libre-tube/LibreTube

app/src/main/java/com/github/libretube/api/obj/Playlists.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistsAdapter.kt, app/src/main/java/com/github/libretube/ui/dialogs/RenamePlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
=> Update playlist name properly after renaming

app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt
=> Fix crash when bottom sheet is being dismissed

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistBookmarkAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistsAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt, app/src/main/res/layout/playlists_row.xml, app/src/main/res/layout/video_row.xml
The actions can be accessed either with swipe gesture or long presses.
closes #3180
=> Hide button to delete playlist and playlist videos

app/src/main/java/com/github/libretube/ui/dialogs/RenamePlaylistDialog.kt
added a " dismiss() " that closes the dialog if name is same(#3376 )
=> close the dialog if name matched

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix closing video player with auto fullscreen enabled

app/build.gradle, app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt, gradle/libs.versions.toml
=> Fix crashes in `SearchResultFragment`

app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt
Add `NewApi` suppressions needed after the `desugar_jdk_libs` update: #3462
=> Add NewApi suppressions.

app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
Improve the overnight time check in `NotificationWorker`.
=> Improve time check in NotificationWorker.

app/src/main/java/com/github/libretube/ui/views/SliderPreference.kt
=> Fix playback speed preference summary

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/advanced_settings.xml
=> Preference to not play videos automatically

app/src/main/java/com/github/libretube/ui/adapters/SubscriptionGroupChannelsAdapter.kt
=> Fix that channel group items get lost on scrolling

app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
=> Fix displayed information in the short tabs of channels

app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
=> Fix crashes caused by view bindings

app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
=> Fix crashes in downloads fragment

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
=> Fix crash when adding to playlist while instance down

app/src/main/java/com/github/libretube/ui/extensions/SetupNotificationBell.kt
=> Hide notification bell if notifications disabled

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt
=> Update displayed chapter while scrubbing time bar

app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
=> Fix crash in `TrendsFragment` caused by bindings

app/src/main/java/com/github/libretube/helpers/WindowHelper.kt
This has been a regression introduced by #3450
=> Fix black bar on displays with cutout/notch

app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
=> Fix crash in library fragment due to view bindings

app/src/main/java/com/github/libretube/api/obj/Channel.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
=> Fix crash when a channel doesn't have a description

app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> Add items to watch history when marking as watched

app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
Fixed an issue "creating new playlist"(#3610 )
I try to spam a lot when creating a playlist but it doesn't create multiple playlists
so there is no point to disabling OnClickListener
Please correct me if I'm wrong!!
=> creating new playlist

app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
closes #3597 
closes #3571 
closes #3593 
closes #3637 
closes #3634
=> Fix various crashes caused by view bindings

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> Fix crash in Subscriptions fragment

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/res/drawable/ic_sort.xml, app/src/main/res/layout/fragment_playlist.xml, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/values/array.xml, app/src/main/res/values/strings.xml
=> Sort menu for local and private playlist

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> Fix top margin when viewing video in vertical fullscreen

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
=> Fix crash when sorting playlists

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> Fix that the player controls don't hide after scrubbing

app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
=> Fix opening replies by clicking comment

app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt, app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt, app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt, app/src/main/res/layout/comments_sheet.xml
=> Remember the comments progress, scroll to top button for comments

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
=> Fix importing large playlists or CSV playlist from YT

app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
=> Attempt to fix restoring backups

app/src/main/java/com/github/libretube/helpers/DashHelper.kt, app/src/main/java/com/github/libretube/helpers/DisplayHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Exclude HDR streams when not supported by device

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml
=> Add button to close audio player

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix crash when closing player due to view bindings

app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
=> Fix crash in CommentsMainFragment

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> Fix deleting videos of sorted playlist

app/src/main/java/com/github/libretube/compat/PictureInPictureCompat.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix various Picure in Picture issues

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/helpers/BrightnessHelper.kt
=> Default to the current screen brightness when swipe gestures enabled

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix issues with watch positions

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/enums/SupportedClient.kt, app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/obj/FreeTubeImportPlaylist.kt, app/src/main/java/com/github/libretube/obj/FreeTubeVideo.kt, app/src/main/java/com/github/libretube/obj/PipedImportPlaylist.kt, app/src/main/java/com/github/libretube/obj/PipedImportPlaylistFile.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt, app/src/main/res/values/strings.xml
Closes https://github.com/libre-tube/LibreTube/issues/3816
[x] tested import FreeTube playlists to app
[x] tested export Piped / LibreTube playlists from app
[x] tested export FreeTube playlists from app
=> support freetube playlists import/export

app/src/main/java/com/github/libretube/api/obj/PipedStream.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
=> Show file size in download dialog

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Update watch positions every second to avoid outdated positions

app/src/main/res/layout/dialog_edit_channel_group.xml, app/src/main/res/layout/dialog_subscription_groups.xml, app/src/main/res/layout/fragment_subscriptions.xml
=> Fix channel groups sheet buttons not visible

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix position of FAB when mini player closed

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> Fix that the info in the audio player doesn't update

app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
=> Limit maximum video info length for video of a channel to two lines

app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt, app/src/main/java/com/github/libretube/helpers/ContextHelper.kt, app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
=> Fix crashes when audio and video mode running simultaneously

app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt, app/src/main/java/com/github/libretube/ui/models/SubscriptionsViewModel.kt, app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
=> Fix (disable) notifications for already seen videos

app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
=> Hide upload date for live videos

app/src/main/res/layout/video_row.xml
=> Truncate end of word in video row

app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/res/layout/fragment_playlist.xml
=> Show currently applied playlist sort order

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix crash when long pressing share while loading

app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
=> Re-add the separator in the search results

app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt, app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt
=> Show restart dialog after restoring backup

app/src/main/java/com/github/libretube/api/obj/PipedStream.kt, app/src/main/java/com/github/libretube/api/obj/Streams.kt, app/src/main/java/com/github/libretube/extensions/ContentLength.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt
=> Use the contentLength returned by the API for downloading

app/src/main/java/com/github/libretube/services/DownloadService.kt
* This increases the download speed to around 100 times the one we had earlier, that's significant!
=> Significantly increase download speed using range requests

app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/ui/views/OfflinePlayerView.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt, app/src/main/res/layout/activity_offline_player.xml, app/src/main/res/layout/fragment_player.xml
=> Code refactor: Separate online and offline player

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Don't show auto play countdown if queue is finished

app/src/main/java/com/github/libretube/db/dao/SubscriptionGroupsDao.kt
=> Fix crash when restoring subscription groups

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Keep queue when switching from audio to video mode and vice versa

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix watch positions while playing a playlist or using autoplay

app/src/main/java/com/github/libretube/ui/sheets/DownloadOptionsBottomSheet.kt
=> Fix crash when repeatedly starting offline background player

app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt, app/src/main/res/layout/fragment_audio_player.xml, app/src/main/res/menu/action_bar.xml
=> Fix various background player UI issues

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml
=> Chapters support in audio player

app/src/main/res/layout/fragment_player.xml
=> Increase horizontal padding of player title and description

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/res/layout/fragment_player.xml
=> Fix subscribe button text color and increase corner radius

app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt, app/src/main/res/layout-land/activity_welcome.xml
=> Fix issues with welcome activity landscape layout

app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
=> Hide channel name in channel tabs for shorts and livestreams

app/src/main/res/drawable/ic_playlist.xml, app/src/main/res/layout/playlists_row.xml
=> Refreshed playlist row design

app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_library.xml, app/src/main/res/layout/fragment_subscriptions.xml
=> Show nothing here indicator if home tab is empty

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
changes from #4072 by @general-a
=> Fixed skip button not disappearing

app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt, app/src/main/res/layout/dialog_download.xml
=> Fix download dialog appearance with large font size

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Chapters dialog: highlight current chapter and auto scroll to it

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt, app/src/main/res/layout/fragment_audio_player.xml, app/src/main/res/xml/player_settings.xml
=> Make autoplay toggle in player global and remove autoplay preference

app/src/main/res/layout/fragment_player.xml
=> Fix position of skip SB segment manually button

app/src/main/java/com/github/libretube/ui/adapters/SliderLabelsAdapter.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt, app/src/main/java/com/github/libretube/ui/viewholders/SliderLabelViewHolder.kt, app/src/main/res/layout/playback_bottom_sheet.xml, app/src/main/res/layout/slider_label_item.xml
=> Add presets/shortcuts for playback speed/pitch

app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt, app/src/main/java/com/github/libretube/obj/DownloadStatus.kt, app/src/main/java/com/github/libretube/receivers/NotificationReceiver.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/res/drawable/ic_stop.xml, app/src/main/res/values/strings.xml
=> Notification action to stop download

app/src/main/java/com/github/libretube/db/obj/PlaylistBookmark.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> Dynamically update playlist bookmark title

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/res/values/strings.xml
=> Treat videos as watched when progress is 25%+

app/src/main/res/values-az/strings.xml, app/src/main/res/values-be/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fi/strings.xml, app/src/main/res/values-hi/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-iw/strings.xml, app/src/main/res/values-ja/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-mr/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-or/strings.xml, app/src/main/res/values-pa/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-ru/strings.xml, app/src/main/res/values-si/strings.xml, app/src/main/res/values-sr/strings.xml, app/src/main/res/values-uk/strings.xml, app/src/main/res/values-zh-rCN/strings.xml, app/src/main/res/values-zh-rTW/strings.xml
=> Update strings for hiding watched videos from feed to 25%

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt
=> Fix crash when resetting playback speed

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/res/layout/exo_styled_player_control_view.xml
=> Show time left when clicking player duration

app/schemas/com.github.libretube.db.AppDatabase/13.json, app/src/main/java/com/github/libretube/api/obj/Playlist.kt, app/src/main/java/com/github/libretube/db/AppDatabase.kt, app/src/main/java/com/github/libretube/db/DatabaseHolder.kt, app/src/main/java/com/github/libretube/db/obj/PlaylistBookmark.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistBookmarkAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> Add support for videos count for playlist bookmarks

app/src/main/java/com/github/libretube/api/obj/Segment.kt, app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
* Add `Pair` variable for SponsorBlock segments.
* Improve video length formatting.
=> Improve SponsorBlock functionality

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml
=> Audio player: only show chapters when not empty

app/src/main/java/com/github/libretube/LibreTubeApp.kt, app/src/main/java/com/github/libretube/api/RetrofitInstance.kt, app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt, app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt, app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
=> Fix auth api url when restoring backup in welcome page

app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt
=> Fix crash when selecting certain pitches

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix: watch positions don't retain

app/src/main/java/com/github/libretube/helpers/BackupHelper.kt
=> Fix: Restoring SponsorBlock preferences from backup

app/src/main/res/layout/spinner_preference.xml
=> Fix: Appearnace of SponsorBlock preference on small screens

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> Fix: hide SponsorBlock skip button in miniplayer

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt, app/src/main/res/values-az/strings.xml, app/src/main/res/values-cs/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-el/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-eu/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-hu/strings.xml, app/src/main/res/values-in/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-lt/strings.xml, app/src/main/res/values-lv/strings.xml, app/src/main/res/values-nb-rNO/strings.xml, app/src/main/res/values-pl/strings.xml, app/src/main/res/values-pt-rBR/strings.xml, app/src/main/res/values-pt/strings.xml, app/src/main/res/values-ro/strings.xml, app/src/main/res/values-tr/strings.xml, app/src/main/res/values/strings.xml
=> feat: Include playlist name in toast after succesfully adding video

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
=> fix: too many chapters highlighted in dialog, crash on selection

app/src/main/java/com/github/libretube/helpers/ProxyHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: disabled proxy when lbry stream available

app/src/main/java/com/github/libretube/db/DatabaseHelper.kt, app/src/main/java/com/github/libretube/db/obj/WatchHistoryItem.kt, app/src/main/java/com/github/libretube/extensions/LocalDate.kt, app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/array.xml, app/src/main/res/values/strings.xml
=> feat: add 'Continue watching' section to home tab

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> feat: remember position and tab in subscriptions fragment

app/src/main/java/com/github/libretube/util/DeArrowUtil.kt
see https://github.com/libre-tube/LibreTube/pull/4276#discussion_r1270105548
=> fix: improve filtering of DeArrow titles and thumbnails

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: fullscreen orientation after shorts video

app/src/main/java/com/github/libretube/helpers/ThemeHelper.kt, app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt, app/src/main/res/values/style.xml
=> fix: improve contrast of watch progress on thumbnails

app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
With the release AGP 8.1, [this issue](https://issuetracker.google.com/issues/282544786) has been fixed.
=> fix: use Files.createDirectories()

app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
=> feat: search intent support

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/extensions/ParallelMap.kt
=> fix: preserve the video order of imported playlists

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: play video's default audio track by default

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: only add videos to watch history if playback started

app/src/main/java/com/github/libretube/extensions/SeekBy.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt, app/src/main/res/layout/fragment_audio_player.xml
=> feat: forward and rewind controls for audio player

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
closes #3379
closes #3303
closes #3612
=> fix: crash when download file doesn't exist

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when pip not supported

app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt, app/src/main/res/values/strings.xml
=> fix: regressions introduced by new chapters layout

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt
=> fix: show search history when clearing query

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt, app/src/main/res/values-television/config.xml, app/src/main/res/values/array.xml, app/src/main/res/values/config.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/general_settings.xml
=> feat: preference to force landscape as orientation

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: playback of live videos

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> fix: queue when not starting with first playlist/channel video

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
=> feat: hide status bar if player locked

app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> feat: option to add whole playlist to current queue

app/src/main/java/com/github/libretube/db/obj/WatchPosition.kt, app/src/main/java/com/github/libretube/ui/sheets/ChannelOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt, app/src/main/res/drawable/ic_eye.xml, app/src/main/res/layout/queue_bottom_sheet.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/style.xml
=> feat(queue): options to mark as (un)watched, and remove watched videos

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt, app/src/main/res/layout/fragment_library.xml, app/src/main/res/xml/appearance_settings.xml
=> feat: move playlists sort order to library tab

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml
=> feat: download option in audio player

app/src/main/res/layout/playback_bottom_sheet.xml
=> refactor: change skip silence button from switch to checkbox

app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
=> chore: trim search history entries before saving

app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt
=> fix: wrong indicated download progress

app/src/main/java/com/github/libretube/ui/views/SbSpinnerPreference.kt
=> fix: persistance of sponsorblock category prefs

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
=> fix: crash when removing video from playlist

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
Same issue as in https://github.com/libre-tube/LibreTube/pull/4466.
=> fix(import): correctly import playlist csv

app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
=> fix: sort order of playlists isn't shown properly

app/src/main/res/layout/fragment_library.xml
=> fix: overflowing issue in sort order option in library

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: restoring playback positions via notification controls

app/src/main/java/com/github/libretube/ui/adapters/NavBarOptionsAdapter.kt, app/src/main/res/drawable/ic_drag_handle.xml, app/src/main/res/drawable/ic_home_dark.xml, app/src/main/res/layout/nav_options_item.xml
=> UI ft: New Drag Handle & Dark Home Icon in NavBar Options Dialog

app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
=> fix: crash when opening library due to unmigrated playlists sort order pref

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> feat(playlist): navigate to uploader on click

app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt, app/src/main/res/layout/queue_bottom_sheet.xml
=> fix: dismiss button in queue sheet

app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt, app/src/main/res/layout/playback_bottom_sheet.xml
=> fix: remove useless buttons to reset pitch and playback speed

app/src/main/res/layout/playlists_row.xml
=> feat: use elevated accent color for playlist videos count

app/build.gradle, app/src/main/java/com/github/libretube/db/obj/SubscriptionGroup.kt, app/src/main/java/com/github/libretube/ui/adapters/SubscriptionGroupChannelsAdapter.kt, build.gradle
It is recommended to switch from kapt to KSP: https://developer.android.com/build/migrate-to-ksp
=> chore: Migrate to KSP

app/src/main/java/com/github/libretube/enums/PlayerEvent.kt, app/src/main/java/com/github/libretube/extensions/Intent.kt, app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Read/write the player event enum directly from/to the intent.
=> refactor: Simplify player event handling

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt, app/src/main/res/xml/player_settings.xml
=> fix: restore pause on quit functionality

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt, app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt, app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/UndimmedBottomSheet.kt
=> feat: allow interacting with player while viewing chapters

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> feat: infinite playing queue when auto-insert related streams enabled

app/src/main/res/layout/channel_subscription_row.xml, app/src/main/res/layout/fragment_subscriptions.xml
=> fix: elevation of subscriptions toggle in subscriptions fragment

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
Fixes an issue, whereupon clicking 'Marked as (un)watched' the video progress would not reflect the change.
https://github.com/libre-tube/LibreTube/assets/63370021/def4cdf6-32f3-485c-b60c-a464d0cabae1
=> fix: update video progress

app/schemas/com.github.libretube.db.AppDatabase/15.json, app/src/main/java/com/github/libretube/api/obj/PipedStream.kt, app/src/main/java/com/github/libretube/api/obj/Streams.kt, app/src/main/java/com/github/libretube/db/AppDatabase.kt, app/src/main/java/com/github/libretube/db/DatabaseHolder.kt, app/src/main/java/com/github/libretube/db/obj/DownloadItem.kt, app/src/main/java/com/github/libretube/parcelable/DownloadData.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
=> feat: allow downloading audio based on language

app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt, app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
=> fix: don't update instance preference while dialog visible to user

app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt, app/src/main/res/layout/chapters_row.xml
=> feat: highlight current chapter

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> feat: respect sort order and filters when playing channel group

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/res/layout/bottom_sheet.xml, app/src/main/res/layout/chapters_row.xml
=> fix: chapter layout UI and UX issues

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
=> feat(audio player): show app icon as thumbnail in data saver mode

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/StatsSheet.kt
style: move StatsSheet to sheets package
=> style: move StatsSheet to sheets package

app/src/main/java/com/github/libretube/api/obj/ContentItem.kt, app/src/main/java/com/github/libretube/db/DatabaseHelper.kt, app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
Hides the `Marked as watched` bottom sheet option, if the video is over 90% watched.
=> feat: hide mark as watched when video is watched

app/src/main/java/com/github/libretube/ui/preferences/MainSettings.kt, app/src/main/res/xml/settings.xml
Handle preference screen navigation using XML: https://developer.android.com/develop/ui/views/components/settings/organize-your-settings
=> refactor: Organize preferences using XML

app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt
=> fix: show okay button for multi selection dialogs instead of cancel

app/src/main/java/com/github/libretube/util/OnlineTimeFrameReceiver.kt
=> fix: crash when scrubbing timebar on certain videos

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> fix: long pressing plays wrong channel group

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> feat: elevate miniplayer background color for better distinguishability

app/src/main/res/layout/playlist_bookmark_row.xml, app/src/main/res/layout/trending_row.xml, app/src/main/res/layout/video_row.xml
=> feat: show placeholders for all images

app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> fix: add pagination to subscriptions list

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/sponsorblock_settings.xml
=> feat: preference to disable sponsorblock submit button

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
=> fix: videos played with background player not added to watch history

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
Simplify scrolling to the top using the [`allViews`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#(android.view.View).allViews()) extension.
=> refactor: Use allViews extension

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
=> fix: importing playlists without a header containing its name

app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
=> fix: hide autoplay countdown when miniplayer visible

app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
=> fix: crash when long pressing search result

app/src/main/java/com/github/libretube/ui/adapters/SubscriptionGroupsAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/models/EditChannelGroupsModel.kt, app/src/main/java/com/github/libretube/ui/sheets/ChannelGroupsSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/EditChannelGroupSheet.kt
=> refactor: remove fragment constructors from channel groups sheets

app/proguard-rules.pro
=> fix: Avoid settings crash in release builds

app/src/main/java/com/github/libretube/ui/dialogs/BackupDialog.kt
=> fix: crash when restoring backups

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when the app was closed for a while

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: crash when view handler got destroyed

app/build.gradle.kts, build.gradle.kts, gradle/libs.versions.toml
this versioning will prevent renovate bot conflicts to kotlin, kgp and serialization versions
=> refactor: libs catalog and bump ksp

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/res/xml/sponsorblock_settings.xml
=> fix: default SponsorBlock categories are not being respected

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> fix: wrong channel group shown as selected

app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt
=> feat: parse YouTube links in the search bar

app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/ui/activities/ZoomableImageActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/views/ZoomableImageView.kt, app/src/main/res/layout/activity_zoomable_image.xml
=> feat: zoomable preview of channel avatar and banner

app/src/main/java/com/github/libretube/ui/views/SliderPreference.kt
=> fix: max concurrent download speed preference shows decimals

app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> fix: stick add to playlist, download and share to bottom

app/src/main/java/com/github/libretube/db/obj/SubscriptionGroup.kt
=> fix: crash when importing old backup

app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
=> fix: crash after being idle in comments sheet main fragment

app/src/main/java/com/github/libretube/services/DownloadService.kt
=> fix: buggy icon to pause download

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when starting video upon auto fullscreen

app/src/main/java/com/github/libretube/api/obj/Streams.kt, app/src/main/java/com/github/libretube/extensions/LocalDate.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: date parsing crash due to YouTube AB testing

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt, app/src/main/res/values/strings.xml, app/src/main/res/xml/player_settings.xml
=> feat: option to set default playback speed manually

app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
=> feat: shorten youtube links when sharing video

app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
=> fix: remove view count from continue watching section

app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
=> feat: hide watched videos from featured in homepage when enabled

app/proguard-rules.pro
=> fix: submitting sponsorblock segment returns error

app/src/main/java/com/github/libretube/extensions/Player.kt
=> fix: can't resume playback at end of video

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt, app/src/main/res/drawable/ic_repeat_one.xml, app/src/main/res/values/strings.xml
=> feat: support for repeating video in audio mode

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> fix: queue moves first video to end in background mode

app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt, app/src/main/res/layout/playback_bottom_sheet.xml
=> feat: support for 1.25x playback speed

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt, app/src/main/res/values/strings.xml
=> feat: add undo action after removing video from playlist

app/src/main/java/com/github/libretube/extensions/RunCatchingIO.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> fix: crash when blocked due to too many requests in playing queue

app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
=> fix: hide scroll to top button for replies

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash on startup when auto fullscreen enabled

app/src/main/res/layout/dialog_stats.xml
=> fix: stats for nerds are not scrollable

app/src/main/java/com/github/libretube/ui/preferences/HistorySettings.kt
=> fix: watch positions can't be reset

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
=> fix: new created playlist not immediately visible

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> fix: repeat all doesn't work if auto-insert to queue is enabled

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: show exit fullscreen button on auto-fullscreen for shorts

app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/ChannelOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> feat: show title/name in playlist/video/channel bottom sheet

app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> fix: show error message toast when playlist is not available

app/src/main/java/com/github/libretube/util/TextUtils.kt
=> fix: upload date shown as 0 weeks ago in some cases

PRIVACY_POLICY.md
=> chore: add ref to SponsorBlock Privacy Policy and ToS to privacy policy

app/src/main/java/com/github/libretube/extensions/Player.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: video can't be resumed after pausing it

app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
=> fix: background service audio playback when screen locked

app/src/main/java/com/github/libretube/db/DatabaseHelper.kt, app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
Fixes a problem where, due to the way recycler views work, the show highlight was not reset properly, causing the highlight to be displayed on the wrong users.
=> fix: properly apply creator highlight

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: increase area that can be used to control the time bar

app/src/main/java/com/github/libretube/ui/dialogs/VoteForSegmentDialog.kt, app/src/main/res/values/strings.xml
=> fix: crash when trying to vote while there are no sb segments yet

app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt, app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt, app/src/main/res/values/strings.xml
=> feat: show toast if the bottom/end of comments/replies is reached

app/src/main/res/layout-land/fragment_player.xml, app/src/main/res/layout/activity_main.xml
=> fix: light theme setting doesn't work properly

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/interfaces/PlayerOptions.kt, app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt, app/src/main/java/com/github/libretube/ui/sheets/SleepTimerSheet.kt, app/src/main/java/com/github/libretube/ui/tools/SleepTimer.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/res/drawable/ic_sleep.xml, app/src/main/res/layout/sleep_timer_sheet.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/general_settings.xml
=> feat: new sleep timer (integrated into the player UI)

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: player resolution updates upexpectedly on fullscreen change

app/src/main/java/com/github/libretube/ui/dialogs/DeleteAccountDialog.kt
=> fix: crash when deleting account

.github/uploader.py
=> chore: fix nightly builds

README.md
Added more links and improved markup
=> chore: improve the "License" section in readme

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
=> feat: automatically play the next downloaded video in offline audio mode

app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> refactor: match the size of continue watching and related streams

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/res/layout-land/fragment_player.xml, app/src/main/res/layout/description_layout.xml, app/src/main/res/layout/fragment_player.xml, app/src/main/res/values/style.xml
=> style: new player layout and various UI improvements

app/src/main/java/com/github/libretube/helpers/BackupHelper.kt, app/src/main/java/com/github/libretube/ui/dialogs/BackupDialog.kt
=> fix: home tab content not included in preferences backup

ROADMAP.md
Let them know that you don't plan to do this yet so that no more duplicate issues are opened.
=> chore(roadmap): add direct use of NPE, YTjs as not planned

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/res/layout/fragment_player.xml, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/values/style.xml
=> style: various player UI improvements, fix navigation bar color

app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/ui/adapters/AddChannelToGroupAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/LegacySubscriptionAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt, app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt, app/src/main/java/com/github/libretube/ui/extensions/SetupSubscriptionButton.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/AddChannelToGroupSheet.kt, app/src/main/java/com/github/libretube/ui/sheets/ChannelOptionsBottomSheet.kt, app/src/main/java/com/github/libretube/ui/viewholders/AddChannelToGroupViewHolder.kt, app/src/main/res/layout/add_channel_to_group_row.xml, app/src/main/res/layout/add_channel_to_group_sheet.xml, app/src/main/res/values/strings.xml
=> feat: quick actions to add a channel to a group

app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt, app/src/main/res/values/strings.xml
=> feat: display the instance uptime on initial instance selection

app/src/main/java/com/github/libretube/api/obj/PipedInstance.kt, app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt, app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt, app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
=> feat: show instance regions, uptime and registration status in settings

app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt, app/src/main/res/layout/slider_label_item.xml
=> feat: add preset to use 1.75x playback speed

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/views/DropdownMenu.kt
=> fix: crash in add to playlist dialog if playlists empty

app/build.gradle.kts, app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, gradle.properties
also migrate buildconfig to dsl from gradle properties as it will get removed in gralde 9.0 release
=> refactor(fix): fix black screen and delay when unsetting fullscreen

app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
=> fix: crash when playing deleted playlist in background

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
=> fix: add to playlist dialog doesnt show any playlists

app/src/main/java/com/github/libretube/ui/extensions/ViewAnimations.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt
Adds support for closing the video being played when the user downswipes the MiniPlayer.
https://github.com/libre-tube/LibreTube/assets/40279132/4d0a4a0a-ab84-4ec3-9c19-c51852dedd41
closes #2020
=> feat: support close video on MiniPlayer swipe down

app/src/main/java/com/github/libretube/ui/activities/AddToQueueActivity.kt
=> feat: start playing video when using add to queue action if queue empty

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: regressions by persistent notification lifecycle fix

app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
=> fix: correctly display transparent channelImages

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml
Add support for setting the sleep timer on the Audio player.
closes #5418 
https://github.com/libre-tube/LibreTube/assets/40279132/10a89cac-657c-45a2-9996-07b57e3747e5
https://github.com/libre-tube/LibreTube/assets/40279132/32c68fa1-80e9-41a1-87d7-da4d67231975
=> feat: Support setting sleep timer on Audio player

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> fix: can't open channel from player fragment

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> fix: improve solo queue repetition performance and make independent of autoplay

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> feat: show repeat button in audio player when playback finished

app/schemas/com.github.libretube.db.AppDatabase/17.json, app/src/main/java/com/github/libretube/db/AppDatabase.kt, app/src/main/java/com/github/libretube/db/obj/Download.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt, app/src/main/res/layout/downloaded_media_row.xml
=> feat: show duration in downloads and improve downloads UI

baselineProfile/build.gradle.kts
* Updated the generated baseline and startup profiles with the latest changes.
* Updated the baseline profile generation configuration.
=> Update baseline profile configuration

app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/DownloadOptionsBottomSheet.kt, app/src/main/res/layout/fragment_downloads.xml
=> feat: option to shuffle downloads in background

.github/workflows/lint.yml
This should fix the EOF issue I think: https://github.com/ScaCap/action-ktlint/issues/47
=> Update ktlint action to v1.8

app/src/main/java/com/github/libretube/enums/NotificationId.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/services/PlaylistDownloadEnqueueService.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
see https://github.com/libre-tube/LibreTube/pull/5525#discussion_r1461333601
=> refactor: store notification ids in an enum

app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/res/layout/fragment_downloads.xml, app/src/main/res/values/strings.xml
Button to delete all downloaded videos at once #5526
I have added delete button to delete all downloaded videos at once.
=> feat: button to delete all downloads

app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
=> fix: replay video from notification player

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/res/layout/exo_styled_player_control_view.xml
=> fix: player seekbar can be hard to grab

app/src/main/java/com/github/libretube/db/obj/LocalPlaylist.kt, app/src/main/java/com/github/libretube/db/obj/LocalPlaylistItem.kt, app/src/main/java/com/github/libretube/helpers/BackupHelper.kt
=> fix: crash when importing a playlist whose id already exists

app/src/main/java/com/github/libretube/ui/models/HomeViewModel.kt
`runBlocking` should not be called within a suspend function.
=> fix: Remove inappropriate runBlocking call

app/src/main/java/com/github/libretube/ui/models/HomeViewModel.kt
https://github.com/libre-tube/LibreTube/pull/5593
=> fix: homepage not loading when trends disabled

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> feat: stop loading after long unsuccessful buffering

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt, app/src/main/res/values/array.xml, app/src/main/res/values/strings.xml, app/src/main/res/xml/player_settings.xml
=> refactor: settings reorganization to improve UX

app/src/main/res/layout/dialog_text_preference.xml
=> fix: SponsorBlock UserID field only accepts numeric inputs

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
=> fix: reduce concurrency of playlist import api calls

app/src/main/java/com/github/libretube/api/obj/StreamItem.kt
=> fix: some livestreams are not filtered out in videos filter

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
=> refactor: don't recreate player on orientation change

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> feat(player): support for keyboard navigation

app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/res/layout/fragment_channel.xml, app/src/main/res/layout/fragment_playlist.xml
This is a revision of a previous pull request : #5568
This is the description copied from that PR. 
//////////////////////////////////////////////////////////////
This pull request makes the following changes:
Partially addresses issue [#4282](https://github.com/libre-tube/LibreTube/issues/4282)
Resolves stuttering for ChannelFragment and PlaylistFragment. Could not fix SubscriptionsFragment because toggling function between Subscriptions and Channels did not work. Will have to revisit.
=> fix: resolve stuttering when scrolling to the bottom of channel/playlist videos list

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> feat: watch positions support for downloaded media

app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: paused video autoplays when unlock screen after few minutes locked

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
=> fix: miniplayer minimized when opening video via link

app/src/main/java/com/github/libretube/ui/sheets/FilterSortBottomSheet.kt
=> fix: poor subscriptions filter options menu performance

app/src/main/AndroidManifest.xml
=> fix: settings activity quickly switches to landscape mode before returning to portrait mode

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash after resuming from locked screen with comments/chapters opened

app/src/main/java/com/github/libretube/api/JsonHelper.kt
=> fix: crash when subscription avatar is null on export

app/src/main/res/layout/fragment_watch_history.xml
=> fix: items cut off in watch history

app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt, app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
=> fix: false message about no comments and scroll to top button

app/src/main/res/layout-land/fragment_player.xml, app/src/main/res/layout/fragment_player.xml, app/src/main/res/layout/fragment_subscriptions.xml
see https://github.com/libre-tube/LibreTube/discussions/5247#discussioncomment-8787935
=> fix: icon color of toggle comments button

app/src/main/java/com/github/libretube/db/DatabaseHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
closes https://github.com/libre-tube/LibreTube/issues/5767
=> fix: respect feed filter on home tab

app/src/main/java/com/github/libretube/ui/adapters/CommentPagingAdapter.kt
=> fix: comment expands when tapping in timestamp

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: autoplay stops after turning screen off

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: back gesture doesn't work on some devices

app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt
=> fix: search is showing inappropriate results

app/src/main/java/com/github/libretube/ui/adapters/SubscriptionGroupsAdapter.kt
=> feat: show confirm modal before deleting channel group

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: autofullscreen stops working after orientation change

app/src/main/java/com/github/libretube/ui/adapters/CommentPagingAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt, app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt, app/src/main/java/com/github/libretube/ui/models/sources/CommentRepliesPagingSource.kt
see https://github.com/libre-tube/LibreTube/issues/5821
closes https://github.com/libre-tube/LibreTube/issues/5746
=> fix: various comment/replies related issues

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
=> style: fix typo

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
=> feat: respect swipe controls option in audio mode

app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
=> style: properly apply pure black/white themes to navigation bar

app/src/main/java/com/github/libretube/ui/dialogs/DownloadPlaylistDialog.kt, app/src/main/res/layout/dialog_download_playlist.xml
=> fix: DownloadPlaylistDialog overflowing on small devices

app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt, app/src/main/res/layout/dialog_submit_segment.xml
closes https://github.com/libre-tube/LibreTube/issues/5897
=> fix: submit segment dialog closes when there are no segments yet

app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt
=> feat: automatically scroll to current chapter

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
(It's called just a few lines above)
=> fix: remove setUsePlatformDiagnostics being called twice

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
closes https://github.com/libre-tube/LibreTube/issues/5764
=> fix: video links dont open on android 10 and below

app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
=> fix: status bar doesn't follow app theme

app/src/main/java/com/github/libretube/util/ExceptionHandler.kt
=> fix: don't crash app when cronet thread fails

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: auto fullscreen causes player layout issues

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when ending player service / fragment

app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
=> fix: crash when skip buttons enabled

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: repeat current doesn't work if autoplay disabled

app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
=> fix: search results scroll state not preserved when rotating

app/src/main/java/com/github/libretube/ui/activities/DownloadActivity.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
=> fix: download activity not dismissed when dialog closed

app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/models/ChaptersViewModel.kt, app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt, app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/ui/views/OfflinePlayerView.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
=> fix: chapters dont work in audio mode

app/src/main/java/com/github/libretube/helpers/ThemeHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: explicitely set status bar color after app start

app/src/main/java/com/github/libretube/ui/fragments/ChannelContentFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
=> fix: crash when refreshing channel page

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: navigation bar missing nav items after closing player

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> feat: remember selected channel group across app restarts

app/src/main/java/com/github/libretube/ui/extensions/SetupSubscriptionButton.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2168463357
=> fix: hide add to group button when not subscribed

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/fragment_audio_player.xml, app/src/main/res/values/style.xml
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2168844868
=> style: make audio player align with status bar color

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when entering audio mode via pip

app/build.gradle.kts, app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt, app/src/main/res/layout/dialog_submit_segment.xml, app/src/test/java/com/github/libretube/TextParserTest.kt, gradle/libs.versions.toml
=> feat: support for duration inputs in submit segment dialog

app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
=> fix: respect sort order when playing private playlist

app/src/main/res/layout/dialog_submit_segment.xml
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2201764558
=> fix: input method for submitting sponsorblock segments

app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/res/layout/fragment_channel.xml
=> feat: button to play recent videos from a channel

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/res/layout/fragment_downloads.xml, app/src/main/res/values/array.xml
Adds enhancement mentioned in issue #6162
closes #6162 
https://github.com/libre-tube/LibreTube/assets/57549340/7eb3c39a-0038-4a97-85b8-2f19c3e9de10
=> feat: added sorting method in downloads

app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt, app/src/main/res/drawable/ic_arrow_left_right.xml, app/src/main/res/layout/dialog_submit_segment.xml
=> feat: button to swap sponsorblock segment start and end time

app/build.gradle.kts, app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt, app/src/test/java/com/github/libretube/TextParserTest.kt, gradle/libs.versions.toml
=> fix: bugs in time parsing logic causing false (milli) second count

app/src/main/res/layout/activity_welcome.xml
=> fix: welcome activity text in light mode

app/src/main/java/com/github/libretube/ui/activities/AboutActivity.kt, app/src/main/res/layout/activity_about.xml
=> feat: improve about activity and device info dialog

app/src/main/res/layout/description_layout.xml, app/src/main/res/layout/fragment_audio_player.xml, app/src/main/res/layout/fragment_channel.xml, app/src/main/res/layout/fragment_playlist.xml
=> feat: make video, playlist, channel title/description selectable

app/src/main/java/com/github/libretube/ui/fragments/SearchSuggestionsFragment.kt
=> fix: crash when search view destroyed before suggestions fetched

app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
=> feat: use watch position as timestamp when sharing

app/src/main/java/com/github/libretube/api/StreamsExtractor.kt, app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt
closes https://github.com/libre-tube/LibreTube/issues/6391
closes https://github.com/libre-tube/LibreTube/issues/6393
=> fix: crashes and issues with local stream extractor

app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
=> feat: support download of private playlists via external downloader

app/src/main/java/com/github/libretube/api/StreamsExtractor.kt
=> fix: related streams published 54 years ago with local extractor

app/src/main/java/com/github/libretube/api/StreamsExtractor.kt
=> feat: download support for local streams extractor

app/src/main/java/com/github/libretube/api/StreamsExtractor.kt
=> fix: videos in watch history uploaded in 1970

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
=> fix: laggy behavior when using back gesture to minimize player

app/src/main/java/com/github/libretube/ui/interfaces/PlayerGestureOptions.kt, app/src/main/java/com/github/libretube/ui/listeners/PlayerGestureController.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: double click gesture inaccurate in landscape player

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: no chapters shown if video highlight is the only chapter

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: wrong chapter name shown if following video has only SB highlight

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/obj/YouTubeWatchHistoryFileItem.kt
=> fix: crash when importing private videos in watch history

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
=> fix: can't paste channel/playlist urls to search bar

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
=> fix: import of new FreeTube playlist format

app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt, app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt, app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt, app/src/main/res/layout/activity_nointernet.xml
=> feat: audio player support for no internet activity

app/src/main/java/com/github/libretube/ui/activities/AddToPlaylistActivity.kt
=> fix: crash in add to playlist dialog upon api error

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt, app/src/main/java/com/github/libretube/obj/FreeTubeImportPlaylist.kt, app/src/main/java/com/github/libretube/obj/FreeTubeVideo.kt
closes https://github.com/libre-tube/LibreTube/issues/6659
=> fix: incorrect FreeTube playlist export

app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
=> fix: crash viewing live video in playlist

app/src/main/java/com/github/libretube/api/obj/StreamItem.kt, app/src/main/java/com/github/libretube/db/obj/WatchHistoryItem.kt, app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> fix: hide download buttons when current video is live

app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
=> fix: live videos shown as uploaded in 1970 in watch history

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/obj/YouTubeWatchHistoryFileItem.kt
=> fix: ignore youtube import entries with missing title url

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
=> fix: crash when two media sessions coexist

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: missing indicator for current selected resolution

app/src/main/java/com/github/libretube/helpers/ImageHelper.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
=> fix: crash when starting audio player

app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: video aspect ratio ignored when playing videos offline

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
=> fix: pressing video notification when playing offline

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
=> fix: crash when videoId is unitialized

app/src/main/java/com/github/libretube/ui/tools/SleepTimer.kt
=> fix: sleep timer doesn't work if playing downloads offline

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: auto fullscreen for shorts

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
=> fix: starting video from queue when autoplay countdown enabled

app/src/main/java/com/github/libretube/extensions/MediaController.kt, app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/adapters/PlayingQueueAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt, app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt, app/src/main/java/com/github/libretube/util/PlayingQueue.kt
=> refactor: simplify playing queue listener handling

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: error toasts when switching between audio/video playback

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
=> fix: autoplay countdown continues although other video selected

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: crash when trying to play downloaded video offline

app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
=> fix: crash when starting next video before current started

app/src/main/java/com/github/libretube/enums/SupportedClient.kt, app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt, app/src/main/res/values/strings.xml
=> feat: support for importing playlist as list of video ids / urls

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
=> refactor: use skip/previous buttons from DefaultMediaNotificationProvider

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
=> fix: exported playlists in urlsorids format use invalid url format

app/src/main/java/com/github/libretube/helpers/NavBarHelper.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt, app/src/main/java/com/github/libretube/ui/activities/SettingsActivity.kt, app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt, app/src/main/java/com/github/libretube/ui/extensions/OnBackPressed.kt, app/src/main/java/com/github/libretube/ui/extensions/SetupFragmentAnimation.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/NoInternetFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SearchSuggestionsFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt, app/src/main/res/layout/activity_nointernet.xml, app/src/main/res/layout/fragment_nointernet.xml, app/src/main/res/navigation/nav_nointernet.xml
=> feat: support for predictive back gestures

app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
for better debuggability of #6860
=> refactor: directly add loaded videos to playlist to improve UX

app/src/main/java/com/github/libretube/enums/ImportFormat.kt
=> chore: change freetube file extension to db

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
see https://github.com/libre-tube/LibreTube/issues/6793#issuecomment-2491027281
=> fix: watch history imports from other languages

app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
see https://github.com/libre-tube/LibreTube/issues/6886
=> fix: only display playlist video count if ge zero

app/src/main/res/layout/dialog_play_offline.xml
=> fix: missing horizontal padding in play offline dialog

app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/res/layout/activity_nointernet.xml
=> fix: wrong predictive back order in offline downloads

app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
see https://github.com/libre-tube/LibreTube/issues/6875#issuecomment-2583240335
=> fix: crash when all caught up view appearing in subscriptions

app/src/main/java/com/github/libretube/db/dao/SubscriptionsFeedDao.kt, app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
=> feat(LocalFeedRepository): don't fetch ChannelInfo if latest channel video is already known

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadPlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/dialogs/ImportTempPlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt, app/src/main/java/com/github/libretube/util/TextUtils.kt
=> fix: backup file names contain (for some file systems) invalid char ':'

app/src/main/res/layout/activity_nointernet.xml
=> fix: offline audio player hidden behind content fragment

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/res/values/strings.xml
This PR adds a dialog that appears at every update showing a new message with important information about settings that should be changed in case of issues.
=> feat: add update info dialog to inform users about current Piped situation

app/src/main/java/com/github/libretube/ui/sheets/ChannelGroupsSheet.kt
=> fix: unable to create new channel groups

app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> fix: mark as (un)watched button

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: MediaCodecRendererException when rotating screen

app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
=> fix: update play pause button on screen rotation

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: update miniplayer play pause button on screen rotation

app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt, app/src/main/res/navigation/nav.xml
Fixes https://github.com/libre-tube/LibreTube/issues/6991
=> Fix backstack when opening search fragment

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
=> fix: add offline played videos to watch history too

app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
=> fix: crash when seeking backwards to negative time

app/src/main/java/com/github/libretube/constants/IntentData.kt, app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/FilterSortBottomSheet.kt, app/src/main/res/layout/filter_sort_sheet.xml, app/src/main/res/values/strings.xml
=> feat: option to hide upcoming videos from feed

app/src/main/java/com/github/libretube/helpers/LocaleHelper.kt, app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
this fixes a regression from https://github.com/libre-tube/LibreTube/pull/7047
=> fix: app language doesn't change on main activity

app/src/main/java/com/github/libretube/helpers/ThemeHelper.kt
regression from https://github.com/libre-tube/LibreTube/pull/7077
=> fix: can't change app icon (debug versions only)

app/src/main/java/com/github/libretube/ui/sheets/EditChannelGroupSheet.kt
Fixes https://github.com/libre-tube/LibreTube/issues/7080
=> fix: crash when opening edit channel group sheet

app/src/main/res/layout/bottom_sheet.xml
=> fix: limit bottom sheet titles to two lines

app/src/main/java/com/github/libretube/db/obj/Download.kt
=> fix: wrong date for downloaded items in watch history

app/src/main/java/com/github/libretube/api/StreamsExtractor.kt, app/src/main/java/com/github/libretube/api/obj/StreamItem.kt, app/src/main/java/com/github/libretube/db/dao/SubscriptionsFeedDao.kt, app/src/main/java/com/github/libretube/extensions/ToID.kt, app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
=> fix: no shorts in locally generated subscriptions feed

app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt, app/src/main/java/com/github/libretube/repo/FeedRepository.kt, app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt, app/src/main/java/com/github/libretube/repo/PipedAccountFeedRepository.kt, app/src/main/java/com/github/libretube/repo/PipedNoAccountFeedRepository.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/models/SubscriptionsViewModel.kt, app/src/main/res/layout/fragment_subscriptions.xml, app/src/main/res/values/strings.xml
=> feat: add progress indicator for local feed extraction

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: manual sponsorblock skip button not showing up

app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
this fixes regressions caused by https://github.com/libre-tube/LibreTube/pull/6971
=> fix: various bugs when deleting single or all downloads

app/schemas/com.github.libretube.db.AppDatabase/20.json, app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt, app/src/main/java/com/github/libretube/db/AppDatabase.kt, app/src/main/java/com/github/libretube/db/dao/LocalSubscriptionDao.kt, app/src/main/java/com/github/libretube/db/obj/LocalSubscription.kt, app/src/main/java/com/github/libretube/repo/LocalSubscriptionsRepository.kt, app/src/main/java/com/github/libretube/repo/PipedLocalSubscriptionsRepository.kt
=> feat: locally store channel info when local streams extraction enabled

app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
=> fix: sort channels alphabetically on client side

app/src/main/java/com/github/libretube/extensions/ToID.kt, app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
=> fix: can't load music playlists using local extraction

app/src/main/res/layout/sleep_timer_sheet.xml
=> fix: label of sleep timer input field overlapping

README.md
closes https://github.com/libre-tube/LibreTube/issues/7194
=> chore: update readme to reflect recent addition of full local extraction

app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
closes https://github.com/libre-tube/LibreTube/issues/7234
=> fix: urls with timestamps don't work properly

app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
=> fix: download tab scrolls to bottom when entered

app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt, app/src/main/res/layout/fragment_download_content.xml
=> fix: download fragment buttons overlap miniplayer

app/src/main/AndroidManifest.xml, app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt, app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt, app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: background shuffle mode doesn't builder a proper queue

app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt, app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt, app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt, app/src/main/res/xml/appearance_settings.xml
closes https://github.com/libre-tube/LibreTube/issues/7273
=> chore: remove alternative videos layout option

app/src/main/java/com/github/libretube/services/PlaylistDownloadEnqueueService.kt
closes https://github.com/libre-tube/LibreTube/issues/7283
=> fix: skip already downloaded videos when downloading playlists

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
=> fix: missing item metadata when playing download containing video AND audio

app/src/main/res/layout/activity_welcome.xml
| Before                                                                                                              	| After                                                                                                                   	|
|---------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------	|
| ![Welcome screen with left toggle](https://github.com/user-attachments/assets/38e4d69f-3b5a-4ddf-9010-5ce6e8439318) 	| ![Welcome screen with centered toggle](https://github.com/user-attachments/assets/adcbb453-4585-4a48-902b-0f4dec4e2b6c) 	|
=> feat(Welcome): center mode group

app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt, app/src/main/java/com/github/libretube/ui/extensions/SetupSubscriptionButton.kt
=> fix: subscription button state not updated after starting next video

app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt, app/src/main/java/com/github/libretube/ui/models/SubscriptionsViewModel.kt
=> fix: scroll state not reset to latest video after refreshing feed/subscriptions

app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
=> feat: smoothen background player -> new video player and video player -> new background player transitions

app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt, app/src/main/java/com/github/libretube/db/DatabaseHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
=> fix: don't block ui thread while filtering watched videos

fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/en-US/short_description.txt
Due to the addition of the "full local mode", the descriptions displayed on F-Droid need an update.
I'm not 100% sure about the wording, suggestions welcome.
=> chore: update app descriptions in fastlane metadata

app/src/main/java/com/github/libretube/ui/extensions/SetupSubscriptionButton.kt
=> fix: confirm unsubscribe preference only works if disabled instead of enabled

app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
see https://github.com/libre-tube/LibreTube/issues/7342#issuecomment-2830693172
=> fix: automatically log user out when enabling full local mode and no auth instance set

app/src/main/java/com/github/libretube/helpers/ThemeHelper.kt, app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
=> refactor: simplify theme and dark/light mode logic

app/src/main/java/com/github/libretube/enums/SbSkipOptions.kt
fixes https://github.com/libre-tube/LibreTube/issues/7384
=> fix: 'show in seekbar' sponsorblock option causes app to crash

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt, app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
closes https://github.com/libre-tube/LibreTube/issues/7394
=> fix: SponsorBlock segments skipped even if temporarily allowed

app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
=> feat: load cached and downloaded images even if data saver mode disabled

app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: comments sheet not dismissed when next video starts

app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
=> fix: repeat mode doesn't work in offline player

app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, app/src/main/java/com/github/libretube/repo/LocalSubscriptionsRepository.kt, app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
related: https://github.com/libre-tube/LibreTube/issues/7409
=> fix: playlist/subscription imports don't complete for larger data

app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
=> fix: crash when opening other video while in background player

app/src/main/java/com/github/libretube/api/poToken/PoTokenWebView.kt, app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt, app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt, app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
This commit removes several unused imports across the application.
=> Chore: Remove unused imports whole application

app/build.gradle.kts, app/src/main/java/com/github/libretube/helpers/ImportHelper.kt, gradle/libs.versions.toml
=> feat: extract playlist name from filename at YouTube CSV imports

app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/models/PlaylistViewModel.kt
=> fix: last selected playlist is not remembered in AddToPlaylistDialog

app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
=> fix: crash when deleting subsequent downloads

app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt, app/src/main/java/com/github/libretube/ui/models/TrendsViewModel.kt
see https://github.com/libre-tube/LibreTube/pull/7592#discussion_r2249244255
=> refactor: re-use cached home page trends in trends fragment for faster load times

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/services/DownloadService.kt, app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt, app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt, app/src/main/java/com/github/libretube/ui/models/TrendsViewModel.kt
=> refactor: unify error handling to be more robust

app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt, app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
=> fix: auto-fullscreen on shorts stopped working

app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt, app/src/main/java/com/github/libretube/repo/LocalSubscriptionsRepository.kt
see https://github.com/libre-tube/LibreTube/issues/7409
=> feat: add delays between subscription imports to avoid rate limits

app/src/main/java/com/github/libretube/services/DownloadService.kt
=> feat: automatically pause downloads when network changes to metered

app/src/main/res/layout/fragment_nointernet.xml
=> fix: crash when opening app with no internet connection

app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt, app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt, app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt, app/src/main/res/layout/dialog_add_to_playlist.xml, app/src/main/res/layout/dialog_create_playlist.xml, app/src/main/res/layout/dialog_edit_channel_group.xml, app/src/main/res/layout/dialog_subscription_groups.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/style.xml, app/src/main/res/values/themes.xml
The buttons in the dialogs now have similar styles.
=> Feat dialogs buttons style
