- app/build.gradle
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
Use the stable version of `androidx.navigation:navigation-*`
> Update dependencies and use stable version

- app/build.gradle
- app/src/main/java/com/github/libretube/ChannelFragment.kt
- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/java/com/github/libretube/VideoViews.kt
- app/src/main/java/com/github/libretube/adapters/ChannelAdapter.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionAdapter.kt
- app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt
- app/src/main/res/layout/trending_row.xml
- app/src/main/res/layout/video_channel_row.xml
- app/src/main/res/values/colors.xml
- build.gradle
> Update dependencies, improvements, TimeAgo changes, and StreamItem duration

- app/src/main/java/com/github/libretube/PlayerFragment.kt
Closes #49 
Note: this hasn't been tested yet
> Improve share button instance preference.

- app/src/main/java/com/github/libretube/PlayerFragment.kt
The instance ended up missing the last character, so I decided to do it this way.
> Fix share button

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/res/layout/fragment_player.xml
> Added separation of title, description and views/date

- app/src/main/java/com/github/libretube/ChannelFragment.kt
- app/src/main/res/layout/fragment_channel.xml
Adds swipe to refresh on channels fragment.
Fix user unreadable strings that are shown while fetching channel details.
> Add swipe to refresh on channel fragment

- app/build.gradle
- app/src/main/java/com/github/libretube/PlayerFragment.kt
- build.gradle
This should significantly reduce video load times and buffering times when seeking
From my test, it reduced from 3 seconds to 2 when seeking
> Use Cronet in Exoplayer

- app/build.gradle
- app/src/main/java/com/github/libretube/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/PipedApi.kt
- app/src/main/java/com/github/libretube/Settings.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistsAdapter.kt
Needs testing on devices below R, but I don't have any, all my devices are R
> Fix subscription imports on R.

- app/build.gradle
- settings.gradle
Thanks for the catch @TiA4f8R!
> Exclude GMS from exoplayer's cronet dependency

- app/src/main/res/layout/fragment_channel.xml
Changed the layout of the channel page (see picture) like suggested in #27 to make it take less space (if that is still a topic) and removed Description Label for better visuals (could add it again if needed but I think it looks better like that)
>  Update channel page

- app/src/main/java/com/github/libretube/Settings.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/res/drawable/ic_info.xml
- app/src/main/res/drawable/ic_save.xml
- app/src/main/res/layout/channel_search_row.xml
- app/src/main/res/layout/fragment_library.xml
- app/src/main/res/layout/playlist_row.xml
- app/src/main/res/layout/playlist_search_row.xml
- app/src/main/res/layout/playlists_row.xml
- app/src/main/res/layout/video_channel_row.xml
- app/src/main/res/layout/video_search_row.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
1. Changed Save Icon in Player Fragment to a "Add  to List" icon 
2. Fixed black font of playlists in playlist search view
3. Removed video thumbnail border in search and channel fragment
4. Changed video thumbnail width (in search, playlist and channel fragment)
5. Changed channel icon size on search tab
6. Added an About Section in the Settings which opens the website in the users default browser
7. Added maximum video title length in Search View (if longer than 60 chars, the ones that are too much get replaced by "...") #153
> Changed Save Icon in player view, added an About Section in the Settings, search view visual fixes

- app/src/main/res/layout/channel_search_row.xml
My last pr just broke some margins accidently, just fixed it now
> Fixed Channel Search Row

- app/src/main/java/com/github/libretube/Settings.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/settings.xml
Added the support for newpipe subscriptions json file
> newpipe import subs

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/res/values/array.xml
> Fixed Languages with specific countries

- app/src/main/res/layout/fragment_player.xml
Changed Subscription Button and Text Color to fit the other material you colors (#199)
> Changed Sub Button Color to Material You

- app/src/main/java/com/github/libretube/PlayerFragment.kt
Adds repeat button to loop video
> Enable video repeat (loop) button

- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/java/com/github/libretube/myApp.kt
Upon changing quality, it'll go back to the position the video was previously at.
Added @Bnyro audio focus code from #210  to this PR
> Seek back to last position and added Audio Focus to Exo Player

- app/src/main/java/com/github/libretube/AddtoPlaylistDialog.kt
- app/src/main/java/com/github/libretube/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/DownloadDialog.kt
- app/src/main/java/com/github/libretube/LoginDialog.kt
- app/src/main/java/com/github/libretube/SearchFragment.kt
- app/src/main/java/com/github/libretube/SettingsActivity.kt
- app/src/main/res/drawable/ic_home.xml
- app/src/main/res/drawable/ic_library.xml
- app/src/main/res/drawable/ic_subscriptions.xml
- app/src/main/res/layout/dialog_addtoplaylist.xml
- app/src/main/res/layout/dialog_create_playlist.xml
- app/src/main/res/layout/dialog_download.xml
- app/src/main/res/layout/dialog_login.xml
- app/src/main/res/layout/dialog_logout.xml
> Updated navbar icons and Dialogs ui

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/java/com/github/libretube/SponsorBlockSettings.kt
> SponsorBlock Fix

- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/res/values/strings.xml
> Share to YouTube

- app/src/main/java/com/github/libretube/SettingsActivity.kt
> player stops in settings fixed

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/java/com/github/libretube/RouterActivity.kt
- app/src/main/res/values/array.xml
The main part has already been done by @lilcheti , just trying to finish it :)
The router activity checks whether the URI is valid now instead of intent filters because they don't want to work.
> Open Video/Channel/Playlist Links with LT

- app/src/main/java/com/github/libretube/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/SettingsActivity.kt
- app/src/main/java/com/github/libretube/VideoOptionsDialog.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/res/layout/fragment_library.xml
> Create Playlist Btn Rework

- app/src/main/java/com/github/libretube/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/obj/Streams.kt
> Player Fragment Structure + BackBuffer Cache 

- app/src/main/java/com/github/libretube/Library.kt
- app/src/main/res/layout/dialog_addtoplaylist.xml
- app/src/main/res/layout/dialog_create_playlist.xml
- app/src/main/res/layout/dialog_download.xml
- app/src/main/res/layout/dialog_login.xml
- app/src/main/res/layout/dialog_logout.xml
- app/src/main/res/layout/fragment_library.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/layout/fragment_search.xml
> Fix dialog btn colors

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/SettingsActivity.kt
- app/src/main/res/layout/activity_nointernet.xml
- app/src/main/res/values/colors.xml
> noInternetActivity settings btn and fixes

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/res/layout/activity_nointernet.xml
> noInternet Activity crash fixed

- app/src/main/java/com/github/libretube/fragments/SearchFragment.kt
- app/src/main/res/layout/fragment_search.xml
> clear search button

- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionAdapter.kt
- app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt
- app/src/main/res/values/strings.xml
> Live video indication

- app/src/main/java/com/github/libretube/RouterActivity.kt
- app/src/main/java/com/github/libretube/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/UpdateDialog.kt
> open links fixed

- app/src/main/java/com/github/libretube/DownloadService.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/preferences/AdvancedSettings.kt
- app/src/main/res/drawable/ic_download.xml
- app/src/main/res/drawable/ic_folder.xml
- app/src/main/res/layout/channel_subscription_row.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> download location settings and fix

- app/src/main/java/com/github/libretube/adapters/ChannelAdapter.kt
- app/src/main/java/com/github/libretube/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/adapters/RepliesAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionAdapter.kt
- app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt
- app/src/main/java/com/github/libretube/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/VideoViews.kt
- app/src/main/res/menu/action_bar.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
> added missing translations

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/dialogs/CustomInstanceDialog.kt
- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/res/drawable/ic_add_instance.xml
- app/src/main/res/layout/dialog_custom_instance.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/instance_settings.xml
> Custom instance

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> related streams toggle

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> added support for time stamped links

- app/src/main/java/com/github/libretube/BackgroundMode.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/DescriptionAdapter.kt
> Player notification thumbnail and description

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/SponsorBlockSettings.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/sponsorblock_settings.xml
Preview, Filler & Music Offtopic
> Added New SponsorBlock Categories

- .github/workflows/tg-bot.yml
Reverts libre-tube/LibreTube#489
> Revert "Bump actions/setup-python from 3 to 4"

- app/src/main/res/layout/playlist_row.xml
- app/src/main/res/layout/trending_row.xml
- app/src/main/res/layout/video_channel_row.xml
- app/src/main/res/layout/video_search_row.xml
Just wrapped `thumnail_duration` TextView in a CardView to get those rounded corners
Before:
After:
> Wrapped thumbnail-duration text in a CardView

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> added player video format option

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
Adds autoplay with a toggle in Settings -> Advanced under Player
> Implement autoplay

- app/src/main/java/com/github/libretube/dialogs/CustomInstanceDialog.kt
- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/fragments/Library.kt
- app/src/main/res/drawable/ic_login.xml
- app/src/main/res/drawable/ic_login_filled.xml
- app/src/main/res/layout/dialog_custom_instance.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/instance_settings.xml
> custom instance frontend url

- app/src/main/java/com/github/libretube/preferences/MainSettings.kt
- app/src/main/res/xml/settings.xml
"About" seems to always be at the bottom of menus (?)
outside of maybe "Exit", which isn't available in this one.
> "About" moved to the bottom

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/AppearanceSettings.kt
- app/src/main/res/drawable/ic_skip.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> seek increment option

- app/src/main/res/layout/exo_styled_player_control_view.xml
> Seek text fix

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/BackgroundMode.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/DescriptionAdapter.kt
> notification click && subtitles fix

- app/src/main/res/layout/exo_styled_player_control_view.xml
> improve controls margin and size

- app/build.gradle
- build.gradle
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- settings.gradle
Just made some minor changes to the build files.
**Summary of changes:**
1. Moved [repositories to `settings.gradle`](https://developer.android.com/studio/releases/gradle-plugin#settings-gradle) and used [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) to apply plugins.
2. Added indents/white spaces to the app build file.
P.S. The app looks amazing!
> Gradle cleanup

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> use default video player instead of vlc

- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> autoplay for playlists

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/res/drawable/ic_auth.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/instance_settings.xml
> Instance selection for login and fetching

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
> fix fragment order

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/layout/fragment_player.xml
> Player UI improvements

- app/src/main/java/com/github/libretube/fragments/HomeFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/xml/settings.xml
> use system region

- app/src/main/java/com/github/libretube/adapters/PlaylistsAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/dialogs/LogoutDialog.kt
- app/src/main/java/com/github/libretube/dialogs/PlaylistOptionsDialog.kt
- app/src/main/java/com/github/libretube/dialogs/VideoOptionsDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/res/drawable/ic_three_dots.xml
- app/src/main/res/layout/fragment_library.xml
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/fragment_subscriptions.xml
> Add playlist options to the playlist fragment

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
> navigation bar color

- app/src/main/java/com/github/libretube/adapters/ChaptersAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/obj/ChapterSegment.kt
- app/src/main/res/drawable/ic_arrow_right.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/strings.xml
> chapters for fullscreen

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> fix crash when playing video

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/xml/player_settings.xml
> fix defres

- app/src/main/java/com/github/libretube/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/util/ThemeHelper.kt
- app/src/main/res/drawable/ic_invert_colors.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
- app/src/main/res/values/themes.xml
- app/src/main/res/xml/advanced_settings.xml
- app/src/main/res/xml/appearance_settings.xml
- app/src/main/res/xml/instance_settings.xml
> introduce pure theme

- app/src/main/java/com/github/libretube/Globals.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/MainSettings.kt
> small cleanup

- app/src/main/AndroidManifest.xml
- app/src/main/res/xml/network_security_config.xml
> trust user cas

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/dialogs/UpdateDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/obj/VersionInfo.kt
- app/src/main/java/com/github/libretube/preferences/MainSettings.kt
- app/src/main/java/com/github/libretube/util/UpdateChecker.kt
- app/src/main/res/values/array.xml
- app/src/main/res/xml/player_settings.xml
> minor fixes

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/Globals.kt
- app/src/main/java/com/github/libretube/dialogs/VideoOptionsDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
> move the background mode to a service

- app/build.gradle
- app/src/main/java/com/github/libretube/util/RetrofitInstance.kt
- gradle/libs.versions.toml
Closes #182
Potential optimizations in future: Use coil-kt with Cronet too for faster image loading!
> Use cronet call factory for api requests.

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
> fix to the blank space problem of BottomNavBar in Android API<29

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/PlayerSettings.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> option to set default subtitle language

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/DoubleTapListener.kt
- app/src/main/java/com/github/libretube/util/OnCustomEventListener.kt
- app/src/main/java/com/github/libretube/views/CustomExoPlayerView.kt
- app/src/main/res/layout/double_tap_overlay.xml
> refactor double tap in the player to allow other gestures

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/adapters/ChaptersAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/preferences/PlayerSettings.kt
- app/src/main/res/drawable/ic_toggle_off.xml
- app/src/main/res/drawable/ic_toggle_on.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/layout/fragment_subscriptions.xml
- app/src/main/res/xml/settings.xml
> toggle autoplay while playing video

- app/src/main/java/com/github/libretube/adapters/ChannelAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt
- app/src/main/java/com/github/libretube/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/SetWatchProgressLength.kt
- app/src/main/res/layout/trending_row.xml
- app/src/main/res/layout/video_row.xml
> show the already played time on the video thumbnail

- app/src/main/java/com/github/libretube/adapters/TrendingAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/views/CustomExoPlayerView.kt
- app/src/main/res/layout/fragment_player.xml
> fix subscriptions not loading

- app/src/main/java/com/github/libretube/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/preferences/GeneralSettings.kt
- app/src/main/java/com/github/libretube/preferences/HistorySettings.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/history_settings.xml
> add confirmation dialogs to some settings

- app/src/main/java/com/github/libretube/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/fragment_watch_history.xml
- app/src/main/res/layout/playlists_row.xml
- app/src/main/res/layout/watch_history_row.xml
- app/src/main/res/values/strings.xml
> improve watch history

- app/src/main/java/com/github/libretube/Constants.kt
> fix out of range notification id

- app/build.gradle
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/style.xml
> better live stream handling

- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/util/NotificationHelper.kt
- app/src/main/res/drawable/ic_signal.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/notification_settings.xml
> network type for notifcations option

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> show resolution on auto quality

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
> fix for exiting searchBar

- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/fragments/PlaylistFragment.kt
> swipe to remove from playlist

- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/util/PipedApi.kt
- app/src/main/java/com/github/libretube/util/SubscriptionHelper.kt
- app/src/main/res/layout/fragment_subscriptions.xml
> unauthenticated subscriptions

- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> share with time code

- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> background mode playback speed option

- app/src/main/java/com/github/libretube/Globals.kt
- app/src/main/java/com/github/libretube/dialogs/VideoOptionsDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/util/AutoPlayHelper.kt
- app/src/main/res/values/strings.xml
> Playing queue

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/preferences/GeneralSettings.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/general_settings.xml
> break reminder

- app/src/main/java/com/github/libretube/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/style.xml
> swipe to left to delete from history

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/res/drawable/ic_window.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> option to disable PiP

- app/src/main/java/com/github/libretube/MyApp.kt
- app/src/main/java/com/github/libretube/activities/AboutActivity.kt
- app/src/main/java/com/github/libretube/activities/NoInternetActivity.kt
- app/src/main/java/com/github/libretube/api/ResettableLazy.kt
- app/src/main/java/com/github/libretube/extensions/ShowSnackBar.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/interfaces/PlayerOptionsInterface.kt
- app/src/main/java/com/github/libretube/preferences/MainSettings.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/views/PlayerOptionsBottomSheet.kt
- app/src/main/res/drawable/ic_zoom.xml
- app/src/main/res/drawable/snackbar_shape.xml
- app/src/main/res/layout/bottom_sheet.xml
- app/src/main/res/layout/dialog_addtoplaylist.xml
- app/src/main/res/layout/dialog_create_playlist.xml
- app/src/main/res/layout/dialog_custom_instance.xml
- app/src/main/res/layout/dialog_delete_account.xml
- app/src/main/res/layout/dialog_login.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
- app/src/main/res/xml/player_settings.xml
> Resize Mode Pref & Better Dialogs & SnackBars

- app/src/main/java/com/github/libretube/Globals.kt
- app/src/main/java/com/github/libretube/MyApp.kt
- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/models/PlayerViewModel.kt
- app/src/main/java/com/github/libretube/models/PlaylistViewModel.kt
- app/src/main/java/com/github/libretube/models/SearchViewModel.kt
- app/src/main/java/com/github/libretube/util/ConnectionHelper.kt
> Use more ViewModels

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/views/CustomExoPlayerView.kt
> fix status bar

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/preferences/GeneralSettings.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/preferences/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/views/MaterialPreferenceFragment.kt
- app/src/main/res/layout/dialog_text_preference.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/general_settings.xml
> better break reminder pref

- app/src/main/java/com/github/libretube/util/ThemeHelper.kt
> fix material you

- app/src/main/res/values-de/strings.xml
- app/src/main/res/values-fr/strings.xml
- app/src/main/res/values-it/strings.xml
- app/src/main/res/values-iw/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-pt/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values-zh-rCN/strings.xml
- app/src/main/res/values/strings.xml
> rename mystic material to material you

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/extensions/BaseActivity.kt
> attempt to fix languages

- app/src/main/java/com/github/libretube/MyApp.kt
- app/src/main/java/com/github/libretube/preferences/NotificationSettings.kt
- app/src/main/java/com/github/libretube/util/NotificationHelper.kt
- app/src/main/java/com/github/libretube/util/NotificationWorker.kt
> grouped notifications

- app/src/main/java/com/github/libretube/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/dialogs/CustomInstanceDialog.kt
- app/src/main/java/com/github/libretube/dialogs/DeleteAccountDialog.kt
- app/src/main/java/com/github/libretube/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/dialogs/LogoutDialog.kt
- app/src/main/java/com/github/libretube/dialogs/RequireRestartDialog.kt
- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/dialogs/UpdateDialog.kt
- app/src/main/java/com/github/libretube/dialogs/VideoOptionsDialog.kt
- app/src/main/res/layout/dialog_share.xml
- app/src/main/res/values/strings.xml
> Toggle for sharing with time code

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> fix local subs

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> don't seek to watch position when end of video

- app/src/main/java/com/github/libretube/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/models/SubscriptionsViewModel.kt
> load feed in background

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> fix deprecation

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/activities/SettingsActivity.kt
see https://developer.android.com/reference/androidx/activity/OnBackPressedDispatcher
> fix deprecated onBackPressed()

- app/src/main/java/com/github/libretube/fragments/HomeFragment.kt
Reverts libre-tube/LibreTube#1215
> Revert "Fixed Iran region has no videos in feed"

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
Cleared removeSearchFocus which led to open searchHistory. Cleared searchOnCloseListener which is dysfunctional anymore.
> fix for searchview anormal behavior

- app/src/main/java/com/github/libretube/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/views/CustomExoPlayerView.kt
> Pause when unplugging headphones

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> fix time codes

- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/preferences/NotificationSettings.kt
> grey out irrelevant settings

- app/src/main/java/com/github/libretube/api/CronetHelper.kt
> enable http cache for retrofit

- app/src/main/java/com/github/libretube/extensions/SetFormattedDuration.kt
> fix inconsistent label

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/adapters/BottomSheetAdapter.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/util/NotificationHelper.kt
- app/src/main/java/com/github/libretube/util/PreferenceHelper.kt
- app/src/main/res/drawable/ic_badge.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> Indicator for amount of new videos

- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
> fix exo controllers

- app/src/main/java/com/github/libretube/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/models/SubscriptionsViewModel.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
> toast when instance unreachable

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/sponsorblock_settings.xml
> Option to skip segments manually

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/LibreTubeApp.kt
- app/src/main/res/values/strings.xml
Use `NotificationChannelCompat` for notification channel creation.
> Use NotificationChannelCompat.

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
> fix abnormal search suggestions behavior

- app/src/main/java/com/github/libretube/adapters/BackupOptionsAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/BackupDialog.kt
- app/src/main/java/com/github/libretube/extensions/Query.kt
- app/src/main/java/com/github/libretube/obj/BackupFile.kt
- app/src/main/java/com/github/libretube/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/util/BackupHelper.kt
- app/src/main/res/layout/backup_row.xml
- app/src/main/res/layout/dialog_backup.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
> Unified backup settings

- app/src/main/java/com/github/libretube/extensions/Sanitize.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
> sanitize file names

- app/release/output-metadata.json
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> fix abnormal search behavior

- app/src/main/java/com/github/libretube/sheets/VideoOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/adapters/BottomSheetAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/MaterialPreferenceFragment.kt
- app/src/main/java/com/github/libretube/util/AutoPlayHelper.kt
- app/src/main/java/com/github/libretube/util/NavBarHelper.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/layout/bottom_sheet.xml
- app/src/main/res/layout/bottom_sheet_item.xml
- app/src/main/res/layout/dialog_download.xml
- app/src/main/res/values/array.xml
- app/src/main/res/xml/appearance_settings.xml
> catch player errors

- app/src/main/java/com/github/libretube/util/ThemeHelper.kt
> fix the app icon option

- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/themes.xml
> fix navigation bar color

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
> Sort instances and enable leanback support

- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt
> fix deleting downloads

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> add option to limit hls to 1080p

- app/src/main/java/com/github/libretube/constants/PreferenceRanges.kt
- app/src/main/java/com/github/libretube/models/interfaces/DoubleTapInterface.kt
- app/src/main/java/com/github/libretube/models/interfaces/PlayerOptionsInterface.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/SliderPreference.kt
- app/src/main/res/values/array.xml
- app/src/main/res/xml/player_settings.xml
> add pref values

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> add loading interval size option

- app/src/main/java/com/github/libretube/ui/adapters/ChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
> improve alternative trending layout

- app/src/main/res/values/array.xml
> add 4k defres

- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
> fix the abnormal channel behavior

- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlaylistsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
> fix crashes when removing recview items

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Player improvements

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/res/drawable/ic_comment.xml
- app/src/main/res/layout/comments_row.xml
- app/src/main/res/layout/dialog_download.xml
- app/src/main/res/values/strings.xml
> Rename files when downloading + indicate when comments are available

- README.md
- Improved Warning Layout
- Added Quick Links to Submit A Bug Report and Request New Feature
- Fixed Typo in NP vs LT heading
- Improved Scroll to Top button
> Several Enhancements ft. README

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
> Add features to the offline player

- app/src/main/java/com/github/libretube/util/DownloadHelper.kt
> fix downloads on low sdk

- app/src/main/res/layout/dialog_slider.xml
- app/src/main/res/layout/playback_bottom_sheet.xml
- app/src/main/res/xml/audio_video_settings.xml
- app/src/main/res/xml/player_settings.xml
> finer playback speed controls

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
> fix sharing channels

- app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
- app/src/main/res/layout/dialog_share.xml
- app/src/main/res/values/strings.xml
> Customize the share time code

- app/src/main/java/com/github/libretube/extensions/ToDp.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix the floating time bar

- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix the playback speed sheet

- app/src/main/java/com/github/libretube/ui/dialogs/DeleteAccountDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt
> Fix the UI not being refreshing after loggin in or registering

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> Improved now playing notification behavior

- app/src/main/java/com/github/libretube/ui/views/BottomSheet.kt
> Hide sheets on PiP change

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> different player error behavior

- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
> fix the share behavior

- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/res/values/strings.xml
> add to playlist in the background

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Hide System UI upon Hiding the Controller

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/api/obj/Channel.kt
- app/src/main/java/com/github/libretube/api/obj/CommentsPage.kt
- app/src/main/java/com/github/libretube/api/obj/Playlist.kt
- app/src/main/java/com/github/libretube/api/obj/Segments.kt
- app/src/main/java/com/github/libretube/extensions/SetWatchProgressLength.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/ImageHelper.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/layout/channel_subscription_row.xml
- app/src/main/res/layout/dialog_share.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/layout/fragment_watch_history.xml
- app/src/main/res/layout/searchhistory_row.xml
> Minimize the channel description by default

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Sort video qualities

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
> Fix the wrong error on the subscriptions page

- .github/tg.py
- .github/workflows/ci.yml
Recently I opened an [Issue](https://github.com/libre-tube/LibreTube/issues/1567). 
Now you have to set some env variable before merge it. : )
> Sign debug APK.

- app/build.gradle
- app/proguard-rules.pro
> fix the updater

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> fix: correct title for break reminder modal

- .github/workflows/ci.yml
This will help to get rid of deprecated warning in workflow.
> Action version update

- .github/tg.py
- .github/workflows/ci.yml
@FireMasterK It's complete now. :p
> TG upload with pyrogram.

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/sponsorblock_settings.xml
> Show SponsorBlock markersS

- app/src/main/java/com/github/libretube/extensions/FormatShort.kt
- app/src/main/res/values/strings.xml
> Fix for the formatShort crash

- app/src/main/java/com/github/libretube/extensions/Round.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/drawable/ic_shuffle.xml
- app/src/main/res/layout/queue_bottom_sheet.xml
>  add shuffle and clear to playing queue

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> pass the playlist id to the background mode

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/res/layout/dialog_addtoplaylist.xml
> Channel tab fixes

- app/src/main/java/com/github/libretube/ui/adapters/ChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/TrendingAdapter.kt
> Fix crash when invalid extracted stream info

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/obj/NavBarItem.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/NavBarOptionsAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/NavBarOptionsDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/NavBarHelper.kt
- app/src/main/res/menu/bottom_menu.xml
- app/src/main/res/xml/appearance_settings.xml
> fix navbar

- app/src/main/res/values/array.xml
100% translation is completed in weblate now. :p
> Add Bangali in array.

- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/style.xml
<h2>Resolves #1705</h2>
* <h3>Before</h3>
* <h3>After</h3>
<h3>Greek</h3> 
width=450 height=860/>
<h3>French</h3> 
width=450 height=860/>
<h3>Portuguese</h3> 
width=450 height=860/>
> Auto-sizing the video options text

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Expand bottom sheets by default, better backup file name

- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/res/layout/playback_bottom_sheet.xml
> reset btns for speed and pitch

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/extensions/ToastFromMainThread.kt
- app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/res/layout/chapter_column.xml
- app/src/main/res/values/strings.xml
> Chapter time codes

- app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/drawable/ic_check.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
- app/src/main/res/xml/advanced_settings.xml
> Option to confirm unsubscriptions

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/xml/shortcuts.xml
> Add launcher icon shortcuts

- app/src/main/java/com/github/libretube/LibreTubeApp.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/extensions/SetupNotificationBell.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/NotificationSettings.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/java/com/github/libretube/util/NotificationHelper.kt
- app/src/main/java/com/github/libretube/util/NotificationWorker.kt
- app/src/main/java/com/github/libretube/util/PreferenceHelper.kt
- app/src/main/res/drawable/ic_bell.xml
- app/src/main/res/layout/channel_subscription_row.xml
- app/src/main/res/layout/fragment_channel.xml
- app/src/main/res/values/style.xml
> Notification bell to configurate notifications by certain channels

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlayingQueueAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/layout/queue_bottom_sheet.xml
> Play video when clicking queue items

- app/src/main/java/com/github/libretube/extensions/SetupSubscriptionButton.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/playlists_row.xml
> Some UI changes

- app/src/main/java/com/github/libretube/ui/sheets/ExpandedBottomSheet.kt
- app/src/main/res/drawable/ic_locked.xml
- app/src/main/res/layout/video_row.xml
closes #1787
closes #1785
closes #1786
> UI changes

- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
<h3>Closes #1673</h3>
* <h4>Demo</h4>
https://user-images.githubusercontent.com/57897297/200629113-70bdb287-4d3f-4db6-84de-29a56a2175cc.mp4
> natural sort of the subtitles language for easier navigation

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix auto fullscreen

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> fix video sharing

- app/src/main/java/com/github/libretube/extensions/CreateDir.kt
- app/src/main/java/com/github/libretube/obj/DownloadedFile.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/util/DownloadHelper.kt
- app/src/main/java/com/github/libretube/util/ImageHelper.kt
- app/src/main/java/com/github/libretube/util/MetadataHelper.kt
> fix some issues with downloads

- app/src/main/java/com/github/libretube/util/ImageHelper.kt
> fix crash when thumbnail missing

- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
> use a different sponsorblock color

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> attempt to fix captions

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt
- app/src/main/java/com/github/libretube/ui/tools/BreakReminder.kt
> fix search bar issues

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/util/LayoutHelper.kt
> apply grid columns for recommended videos

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix the subtitle size

- app/src/main/res/menu/action_bar.xml
> fix the search behavior

- app/src/main/res/values/strings.xml
> change time code string

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/layout/trending_row.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/appearance_settings.xml
- app/src/main/res/xml/player_settings.xml
> [Option] New Player UI

- app/src/main/java/com/github/libretube/api/obj/PipedStream.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/interfaces/OnlinePlayerOptions.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/drawable/ic_audio.xml
- app/src/main/res/values/strings.xml
Note:
1. The initial audio language is  attempted to be determined by  the app language. 
2. HLS/Auto is not supported for switching the audio track
closes #1841
> Option to change the audio track

- app/src/main/java/com/github/libretube/util/ImportHelper.kt
- app/src/main/res/values/strings.xml
> Improved user feedback on subscription import

- app/build.gradle
- app/src/main/java/com/github/libretube/api/obj/PipedStream.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/obj/VideoResolution.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/DashHelper.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
- gradle/libs.versions.toml
This is so big, that this deserves its own release haha
closes #1849 as it's not a thing anymore
> Implement proper dash support

- app/src/main/res/layout/fragment_playlist.xml
> add playlists padding

- app/src/main/java/com/github/libretube/util/ImageHelper.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
> Add option for runtime caching

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/drawable/ic_reverse.xml
- app/src/main/res/layout/queue_bottom_sheet.xml
> Queue: Reverse and repeat controls

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/ExpandedBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> Option to open queue from background notification

- app/src/main/java/com/github/libretube/util/ImageHelper.kt
> disable disk cache instead of memory cache

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/extensions/ToastFromMainThread.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/extensions/WithMaxSize.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
- app/src/main/java/com/github/libretube/ui/models/HomeModel.kt
- app/src/main/java/com/github/libretube/util/LocaleHelper.kt
- app/src/main/res/layout/fragment_home.xml
- app/src/main/res/layout/fragment_trends.xml
- app/src/main/res/menu/bottom_menu.xml
- app/src/main/res/navigation/nav.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
- app/src/main/res/xml/shortcuts.xml
> New Home Page UI

- app/src/main/java/com/github/libretube/util/ImportHelper.kt
> allow unknown file types for importing subscriptions

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> fix playlists crash

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/MainSettings.kt
> Fix crash on clicking the player share button

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Fix crash on destroy of the player notification

- app/src/main/java/com/github/libretube/services/UpdateService.kt
- app/src/main/java/com/github/libretube/util/DownloadHelper.kt
> fix updater issues

- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
> fix crash when deleting from watch history

- app/src/main/java/com/github/libretube/ui/adapters/SearchSuggestionsAdapter.kt
- app/src/main/res/layout/searchsuggestion_row.xml
> Fill Search Controller When Tapping on Arrow

- app/src/main/java/com/github/libretube/ui/preferences/MainSettings.kt
> show network instead of server error

- app/src/main/AndroidManifest.xml
> support shortcuts for all app icons

- app/src/main/java/com/github/libretube/ui/interfaces/DoubleTapListener.kt
> fix unresponsive controls

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix crash when LBRY available as stream source

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/xml/audio_video_settings.xml
> Fix the watch position pref

- app/src/main/java/com/github/libretube/ui/adapters/IconsSheetAdapter.kt
- app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/ui/sheets/IconsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/viewholders/IconsSheetViewHolder.kt
- app/src/main/java/com/github/libretube/util/ThemeHelper.kt
- app/src/main/res/layout/app_icon_item.xml
- app/src/main/res/values/array.xml
- app/src/main/res/xml/appearance_settings.xml
> Preview App icons in Appearance Settings

- app/src/main/java/com/github/libretube/obj/BackupFile.kt
- app/src/main/java/com/github/libretube/ui/dialogs/BackupDialog.kt
- app/src/main/java/com/github/libretube/util/BackupHelper.kt
> add option to backup bookmarked playlists

- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
> enable save button at player fragment for local playlists

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> option to not auto-insert related videos

- app/src/main/res/layout/activity_nointernet.xml
> Fix the misaligned no-network icon

- app/src/main/java/com/github/libretube/ui/interfaces/DoubleTapInterface.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> pause and play on double click at the center

- app/src/main/java/com/github/libretube/db/obj/LocalPlaylistItem.kt
- app/src/main/java/com/github/libretube/obj/BackupFile.kt
- app/src/main/java/com/github/libretube/ui/dialogs/BackupDialog.kt
- app/src/main/java/com/github/libretube/util/BackupHelper.kt
- app/src/main/res/values/strings.xml
> add possibility to backup and restore local playlists

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Smooth PiP transition

- app/src/main/java/com/github/libretube/ui/extensions/SetInvisible.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Fix the next video button at the player

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/fragment_watch_history.xml
> Show padding for playlist and watch history only if needed

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/adapters/NavBarOptionsAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/NavBarOptionsDialog.kt
- app/src/main/java/com/github/libretube/util/NavBarHelper.kt
- app/src/main/java/com/github/libretube/util/PreferenceHelper.kt
- app/src/main/res/drawable/ic_home_outlined.xml
- app/src/main/res/layout/nav_options_item.xml
- app/src/main/res/values/strings.xml
> add option to set default start tab

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix pip when video ended

- app/src/main/java/com/github/libretube/ui/views/SliderPreference.kt
- app/src/main/res/drawable/ic_remove.xml
- app/src/main/res/layout/dialog_slider.xml
> improve slider dialog accessibility

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> hide the open with button by default

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> finish fullscreen on backpress

- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
> hide downloads tab if already part of navbar

- app/src/main/java/com/github/libretube/ui/interfaces/PlayerGestureOptions.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayerGestureController.kt
> Pinch to zoom

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/res/layout/comments_row.xml
- app/src/main/res/layout/fragment_player.xml
> Comments redesign, wrapped into a bottom sheet

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values-az/strings.xml
- app/src/main/res/values-es/strings.xml
- app/src/main/res/values-hi/strings.xml
- app/src/main/res/values-in/strings.xml
- app/src/main/res/values-lt/strings.xml
- app/src/main/res/values-nb-rNO/strings.xml
- app/src/main/res/values-pl/strings.xml
- app/src/main/res/values-uk/strings.xml
- app/src/main/res/values-vi/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Replace the `Open with` button at the player with PiP

- app/src/main/res/drawable/controls_layout_bg.xml
- app/src/main/res/layout/player_gesture_controls_view.xml
- app/src/main/res/values/style.xml
Fix resizing on text change in view
related to #2084
> Fix gesture control view resize

- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/comments_sheet.xml
- app/src/main/res/values/strings.xml
> Improve the comments sheet

- app/src/main/java/com/github/libretube/extensions/Sanitize.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
fix sanitize of the filename
Closes #1699
> Fix download issue caused by file name

- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
> fix duplicated comments

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/drawable/ic_text.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> add a preference for the captions text size

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Option to disable double tap to seek

- app/src/main/java/com/github/libretube/api/obj/ContentItem.kt
- app/src/main/java/com/github/libretube/api/obj/StreamItem.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/viewholders/VideosViewHolder.kt
- app/src/main/java/com/github/libretube/util/PreferenceHelper.kt
- app/src/main/res/drawable/ic_done.xml
- app/src/main/res/layout/all_caught_up_row.xml
- app/src/main/res/values/strings.xml
> Indicator the the feed got caught up for subscriptions

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
> Fix channel page to display selected chip content

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/api/obj/PlaylistId.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/obj/ImportPlaylist.kt
- app/src/main/java/com/github/libretube/obj/ImportPlaylistFile.kt
- app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt
- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/MainSettings.kt
- app/src/main/java/com/github/libretube/util/ImportHelper.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
- app/src/main/res/xml/import_export_settings.xml
- app/src/main/res/xml/settings.xml
> Playlists import export

- app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/main/res/values/strings.xml
> Add warning dialog if entering an email as username

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> fix opening public playlists

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/dialogs/RenamePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> Show the current name when renaming a playlist

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/adapters/LegacySubscriptionAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/ChannelOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/util/BackgroundHelper.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/values/strings.xml
> Option to shar channels and play their latest videos

- app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/AudioVideoSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/HistorySettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/MainSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/NotificationSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/SponsorBlockSettings.kt
- app/src/main/res/xml/instance_settings.xml
closes #2223 
closes #2232 
closes #2222
> Fix wrong titles of preferences

- app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt
> Show Material You as accent color on Android 12+

- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/layout/queue_row.xml
> same corner radius for all thumbnails

- app/src/main/res/values/style.xml
> use a theme color for the progress

- app/src/main/res/layout/fragment_library.xml
- app/src/main/res/values/style.xml
> Library fragment redesign

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Fix offline player play/pause button

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/AppearanceSettings.kt
- app/src/main/res/values/strings.xml
> Toast when no download source selected

- app/src/main/java/com/github/libretube/ui/dialogs/DeletePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
Update playlist view on when the playlist is changed or deleted.
Closes #2196
> Fix crash on opening deleted local playlist

- app/src/main/java/com/github/libretube/util/ThemeHelper.kt
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
> add empty dracula theme

- app/src/main/java/com/github/libretube/util/ImportHelper.kt
> allow `application/*` as import file type

- app/src/main/res/values/style.xml
> increase fullscreen btn size

- app/src/main/java/com/github/libretube/util/ImportHelper.kt
> fix crash when importing playlists of wrong format

- app/src/main/java/com/github/libretube/services/ClosingService.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/NavBarOptionsAdapter.kt
- app/src/main/java/com/github/libretube/util/NavBarHelper.kt
> Possibility to hide the navbar completely

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> clone playlists without account

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Remember the playback speed per session

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Pause the player when leaving app and PiP disabled

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
Only for local playlists. Not sure if there is any API endpoint to change the thumbnail.
Closes #2317
> Fix playlist thumbnail change when remove first video

- app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt
> fix reversed search suggestions

- app/src/main/java/com/github/libretube/db/dao/PlaylistBookmarkDao.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> update bookmarked playlist thumbnails when changed

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> don't start videos automatically when the data saver mode is enabled

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix not-updating skip/prev buttons

- app/src/main/res/layout/fragment_playlist.xml
> fix overlapping text in the playlist page

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> fix crash at playlist page

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
Preparation for https://github.com/TeamPiped/Piped-Backend/pull/481
cc @FireMasterK
> Parse comments text as HTML

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> don't load thumbnail into notification in data saver mode

- app/src/main/java/com/github/libretube/util/PlayerGestureController.kt
> improve OSD visibility delay when double tap to seek off

- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Hightlight the current resolution in the quality selection

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/obj/ImportPlaylist.kt
- app/src/main/java/com/github/libretube/util/ImportHelper.kt
> Playlists import from YouTube

- app/src/main/java/com/github/libretube/util/BackupHelper.kt
> fix crash when restoring the preferences backup

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Don't start PiP when the video is paused

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Open with button behavior on long pressing `Share`

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
> limit the max height of the comments sheet

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> place the chapter time stamps in front of the chapter name

- app/src/main/java/com/github/libretube/obj/PreviewFrame.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/SeekbarPreviewListener.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Seekbar preview

- app/src/main/java/com/github/libretube/db/obj/LocalPlaylist.kt
- app/src/main/java/com/github/libretube/db/obj/LocalPlaylistWithVideos.kt
> fix crash when restoring a backup with playlists

- app/src/main/res/values/style.xml
> improve the watch progress contrast

- app/src/main/java/com/github/libretube/ui/views/CustomSwipeToRefresh.kt
- app/src/main/res/layout/fragment_trends.xml
> Theme the pull refresh progress

- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/ExpandedBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomSwipeToRefresh.kt
> Hide the comments bottom sheet when entering PiP

- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
> Fix the sorting of playlists in the library

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
> Increase size of alternative related videos

- app/src/main/java/com/github/libretube/extensions/UpdateParameters.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/values/drawables.xml
> Hide captions in PiP and mini-player

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistsAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DeletePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> Remove playlists at library on deletion

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix crash when toggling the video description

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Show the video duration when SponsorBlock segments get skipped

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/DataSaverMode.kt
- app/src/main/java/com/github/libretube/util/ImageHelper.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/res/layout/trending_row.xml
- app/src/main/res/values/array.xml
- app/src/main/res/xml/advanced_settings.xml
> Option to allow data saver on metered networks

- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
- app/src/main/java/com/github/libretube/util/DataSaverMode.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/xml/sponsorblock_settings.xml
>  Fix the SponsorBlock marker height

- app/src/main/java/com/github/libretube/api/obj/CommentsPage.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
> Fix crash during startup caused by the comments sheet

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistBookmarkAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/BookmarksFragment.kt
- app/src/main/java/com/github/libretube/ui/viewholders/PlaylistBookmarkViewHolder.kt
- app/src/main/res/layout/playlist_bookmark_row.xml
- app/src/main/res/layout/playlist_row.xml
> Use playlists layout for bookmarks

- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/main/res/drawable/ic_copy.xml
- app/src/main/res/layout/dialog_create_playlist.xml
- app/src/main/res/values/strings.xml
> Add a Clone Playlist action to the create playlist dialog

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Option to pause the video on leaving the app

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix that watch positions don't work for the queue

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/res/layout/fragment_watch_history.xml
> Add play all and clear actions to watch history

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/res/values/strings.xml
> Add shuffle button to owned playlists

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
> Remember sort order and filter in feed

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/interfaces/PlayerOptions.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Replace the autoplay option with a switch

- app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
> Fix that the last few comments can't be seen

- app/src/main/res/layout/dialog_create_playlist.xml
> Unify the button style of the create playlist dialog

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Add a horizontal margin to the player controls at landscape

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistBookmarkAdapter.kt
- app/src/main/java/com/github/libretube/ui/viewholders/PlaylistBookmarkViewHolder.kt
> Fix the layout of boomarked playlists in the library

- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Improve the queue shuffle behavior

- app/src/main/java/com/github/libretube/extensions/ToPlaylistBookmark.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/res/values/strings.xml
> Add bookmark option to playlist options bottom sheet

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> Set notification badge color to `colorPrimary`

- app/src/main/res/layout/fragment_library.xml
> Fix scroll behavior in library

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> Only load 10 videos at once in private playlists

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
> Fix clicking on private playlists

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
> Fix crash when removing video from playlist

- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
> Allow modifying the queue without restrictions

- app/src/main/java/com/github/libretube/ui/extensions/SetupNotificationBell.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> Fix doubled videos in playlists on reload

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
> Fix that background mode doesn't start from beginning

- app/src/main/res/layout/fragment_player.xml
> Increase the clickable space to toggle the description

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
> Localize the date in the `PlayerFragment`

- app/src/main/java/com/github/libretube/enums/PlayerEvent.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/values/strings.xml
> PiP: Forward and Rewind actions

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/enums/PlayerEvent.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Option for background and skip controls in PiP

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
Use `ServiceCompat` in the background mode service.
> Use ServiceCompat.

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
- app/src/main/res/layout/fragment_audio_player.xml
- app/src/main/res/menu/action_bar.xml
- app/src/main/res/navigation/nav.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> Integrated audio player UI

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/BackgroundHelper.kt
> Keep queue when entering audio mode

- app/src/main/java/com/github/libretube/ui/extensions/SetInvisible.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix visiblity of skip and prev btns when player locked

- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
- app/src/main/res/drawable/ic_playlist_add.xml
- app/src/main/res/layout/queue_bottom_sheet.xml
> Convert queued videos in a playlist

- app/src/main/java/com/github/libretube/util/ImageHelper.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/res/drawable/ic_forward_md.xml
- app/src/main/res/drawable/ic_next_outlined.xml
- app/src/main/res/drawable/ic_prev_outlined.xml
- app/src/main/res/drawable/ic_rewind_md.xml
This PR adds the following to the player notification
* Controls to go to the previous and next video
* Controls to forward and rewind
* The name of the video uploader
The PR also fixes that thumbnails sometimes don't load in the notification.
closes #2624
> Improved player notification

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix that queue doesn't regenerate

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/activities/AddToQueueActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Option to add newly opened links to queue

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> Fix the color of notification badges

- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Fix duplicated videos in the playing queue

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/WindowHelper.kt
> Use compats for setting fullscreen

- app/src/main/java/com/github/libretube/ui/views/TimePickerPreference.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
Simplify the implementation of `TimePickerPreference` using [`LocalTime`](https://docs.oracle.com/javase/8/docs/api/java/time/LocalTime.html).
> Simplify TimePickerPreference.

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackSpeedSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/playback_bottom_sheet.xml
- app/src/main/res/values/strings.xml
> Ability to skip silence when playing videos

- app/src/main/java/com/github/libretube/compat/PendingIntentCompat.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
Add helper methods to `PendingIntentCompat` to avoid issues on API levels < 23.
> Add PendingIntentCompat helper methods.

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
> Fix that skip silence is enabled by default

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
Fixes that the offline player doesn't request audio focus
Improves the buffering for the background mode
> Use the same audio attributes and load control for all players

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Only auto enter PiP when enabled

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Use custom animation handlers for player controls

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/WindowHelper.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Keep space for the status bar in player

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/WindowHelper.kt
> Hide system bars on shorts

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/extensions/SetFormattedDuration.kt
> Fix that live videos are tagged as shorts

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> Fix the different colors of navigation and bottom bar

- app/src/main/java/com/github/libretube/ui/adapters/PlayingQueueAdapter.kt
> Fix queue starts wrong video after reordering

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> Fix the notification thumbnail vanishing

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/res/drawable/ic_video.xml
- app/src/main/res/layout/fragment_audio_player.xml
- app/src/main/res/values/style.xml
> [Audio Mode] Share, playback, queue and open video controls

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
Use the [`bundleOf()`](https://developer.android.com/reference/kotlin/androidx/core/os/package-summary#bundleOf(kotlin.Array)) Kotlin helper method.
> Use bundleOf().

- app/src/main/java/com/github/libretube/api/obj/Channel.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
> Fix channel crashes.

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/SettingsActivity.kt
Use the Kotlin [`OnBackPressedDispatcher.addCallback()`](https://developer.android.com/reference/kotlin/androidx/activity/package-summary#(androidx.activity.OnBackPressedDispatcher).addCallback(androidx.lifecycle.LifecycleOwner,kotlin.Boolean,kotlin.Function1)) extension function.
> Use OnBackPressedDispatcher.addCallback() extension.

- app/src/main/java/com/github/libretube/obj/BackupFile.kt
- app/src/main/java/com/github/libretube/util/BackupHelper.kt
> Fix backup backwards compatibility

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/res/xml/history_settings.xml
> Fix unresponsiveness when opening watch history

- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
> Fix crash in watch history when deleting video

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Show whole title when description visible

- .github/runOnRelease.py
- .github/workflows/run-on-release.yml
You have to set a new Secret **TG_CID** with Value **libretube** and Add the bot in libretubes channel as well.
For example, check  https://t.me/abuneko/467
> Auto Release on TG after GH Release.

- app/src/main/java/com/github/libretube/util/DataSaverMode.kt
- app/src/main/java/com/github/libretube/util/NetworkHelper.kt
- app/src/main/java/com/github/libretube/util/PlayerHelper.kt
Check if the currently connected network is metered in `NetworkHelper`, instead of only whether it is a mobile network.
> Check if the connected network is metered in NetworkHelper.

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/SeekbarPreviewListener.kt
Use the [`View.updateLayoutParams()`](https://developer.android.com/reference/kotlin/androidx/core/view/package-summary#(android.view.View).updateLayoutParams(kotlin.Function1)) extensions.
> Use View.updateLayoutParams() extensions.

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Don't kill the app when closing through PiP

- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
> Fix cloning playlists in the create playlist dialog

- app/src/main/java/com/github/libretube/api/obj/Comment.kt
- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/res/layout/comments_row.xml
- app/src/main/res/layout/comments_sheet.xml
- app/src/main/res/layout/fragment_comments.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/strings.xml
- Comments and replies are now displayed in different fragments making the experience more friendly. (Issue #2878)
- Video is not darkened when comments dialog is opened. (closes #2876)
- closes #2425
- Although video is not dimmed when comments dialog is opened, clicks on the video has no effect until dialog is closed. I could not fix this.
> Fixes #2878 : Using multi-level comments display.

- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
Use OkHttp's [`HttpUrl`](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-http-url/) class to query URL values.
> Use HttpUrl in TextUtils.

- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
Create the backup file timestamp using `DateTimeFormatter`.
> Use DateTimeFormatter to create backup file timestamp.

- app/src/main/java/com/github/libretube/ui/dialogs/CustomInstanceDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DeleteAccountDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LogoutDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/RequireRestartDialog.kt
- app/src/main/java/com/github/libretube/ui/preferences/AdvancedSettings.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
Use [`ActivityCompat.recreate()`](https://developer.android.com/reference/androidx/core/app/ActivityCompat#recreate(android.app.Activity)) to backport the recreate behavior of Android Pie and later on older versions of Android.
> Use ActivityCompat.recreate().

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix watching unprocessed livestreams

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/ui/tools/SleepTimer.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/NavigationHelper.kt
- app/src/main/java/com/github/libretube/util/PlayerGestureController.kt
Use the [`Handler.postDelayed()`](https://developer.android.com/reference/kotlin/androidx/core/os/package-summary#(android.os.Handler).postDelayed(kotlin.Long,kotlin.Any,kotlin.Function0)) extension function.
> Use Handler.postDelayed() extension function.

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Closes comments on auto play video change. Fixes #2898

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/comments_row.xml
- app/src/main/res/layout/comments_sheet.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values/colors.xml
> Added the original comment as the first item in replies.

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/util/BackupHelper.kt
> Reload playlists after successfully cloning

- app/src/main/java/com/github/libretube/helpers/NotificationHelper.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
* Convert `NotificationWorker` to a coroutine worker.
* Use the `PeriodicWorkRequestBuilder` extension.
> Use Work KTX functionality.

- app/src/main/java/com/github/libretube/ui/extensions/SetDrawables.kt
> Fixes: icons not showing in the player menu options.

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
see https://github.com/TeamPiped/Piped-Backend/pull/512
> Use POST requests for unauthenticated subscriptions

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Improve double tap on center of player

- app/src/main/java/com/github/libretube/ui/views/CustomSwipeToRefresh.kt
> Use an elevated surface color for the swipe to refresh

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
see https://github.com/libre-tube/LibreTube/pull/2960#issuecomment-1416868376
> Unauthenticated: Use GET when subs <= 100

- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
Convert the search `RecyclerView` adapter to a [`ListAdapter`](https://developer.android.com/reference/androidx/recyclerview/widget/ListAdapter).
> Convert SearchAdapter to a ListAdapter.

- app/src/main/res/layout/activity_main.xml
- Fixes #2985 app not closing on single back press just after opening the app
> :bug: Fixes single back press not closing app

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Prevent controls from disappearing while scrubbing

- app/src/main/res/drawable/ic_play_circle.xml
- app/src/main/res/drawable/player_switch_thumb.xml
- app/src/main/res/drawable/player_switch_track.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
> New Autoplay switch design

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/DashHelper.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/res/drawable/ic_equalizer.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> Add preference to choose video codecs

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix the time stamp parsing in the `PlayerFragment`

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/values/strings.xml
> Option to mark videos as watched

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/interfaces/PlayerGestureOptions.kt
- app/src/main/java/com/github/libretube/ui/listeners/PlayerGestureController.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt
> Enter/Exit Fullscreen swipe gestures

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/menu/action_bar.xml
> Open audio player from three dot menu

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/res/layout/fragment_audio_player.xml
> Button to quit the audio mode

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/values/array.xml
- app/src/main/res/xml/history_settings.xml
> Option to disable watch positions in audio mode

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix SponsorBlock segment loop at end of video

- app/src/main/java/com/github/libretube/api/obj/Instances.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
> Improve the dynamic instance list fetching

- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
> Improve home page loading behavior

- app/src/main/java/com/github/libretube/extensions/GetWhileDigit.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
> Remember the download selections

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
> Fix compatibility with previous backups

- app/build.gradle
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- gradle/libs.versions.toml
* Add the [ViewBindingPropertyDelegate](https://github.com/androidbroadcast/ViewBindingPropertyDelegate) library.
* Use view binding extensions in the player fragment to avoid memory leaks.
> Use view binding extensions in PlayerFragment.

- app/src/main/res/values/style.xml
- gradle/wrapper/gradle-wrapper.properties
> Use Filter chips for the search, downgrade gradle back to 7.6

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DeleteAccountDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LogoutDialog.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- app/src/main/res/xml/instance_settings.xml
> Better login/register error messages

- app/src/main/java/com/github/libretube/api/obj/Message.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Better error messages when a video is unavailable

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Round the displayed playback speed

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> :bug: Fixes crash on empty playlist shuffle and background playback

- app/src/main/java/com/github/libretube/api/obj/Streams.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
> Display the video category in the description

- .github/workflows/ci.yml
This should take less time from now.
> Add filter in git clone.

- app/src/main/java/com/github/libretube/constants/Constants.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- app/src/main/res/values/array.xml
- app/src/main/res/xml/instance_settings.xml
> Fix that kavin.rocks is not shown as selected by default

- app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
> Fix the displayed chosen instance

- app/src/main/res/values/strings.xml
> Improve the instance summary string

- app/src/main/java/com/github/libretube/db/dao/WatchPositionDao.kt
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
> Convert watch positions dao to coroutines, fix holes in the feed

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix position when auto-playing next video

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix autoplay countdown crash

- app/src/main/java/com/github/libretube/ui/dialogs/BackupDialog.kt
> Fix that backup files might be empty

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> Remove playlists from the playing queue

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
> Fix crash when restoring legacy backup

- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
> Fix negative subscriber and views count for channels

- app/src/main/java/com/github/libretube/db/AppDatabase.kt
- app/src/main/java/com/github/libretube/db/Converters.kt
- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/db/obj/WatchHistoryItem.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
Format the dates for watch history items in the same style as in the video description.
> Format watch history item dates.

- app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Close video player when entering audio mode

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
- app/src/main/res/layout/comments_row.xml
> Clickable comment timestamps

- app/src/main/java/com/github/libretube/ui/views/DropdownMenu.kt
> Fix suggestions after changing the selected video/audio quality

- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/res/values/strings.xml
* Improve the subscriber, playlist uploader and video count formatting.
* Display the correct number of videos in a private playlist after a video is deleted.
> Improve count formatting.

- app/src/main/res/layout/comments_row.xml
> Make comments text selectable manually

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
> Fix the formatting of copied comments

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix SponsorBlock markers and toggle

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
> Fix closing the audio player

- app/src/main/java/com/github/libretube/extensions/UpdateParameters.kt
Convert the updateParameters() extension function to an [inline function](https://kotlinlang.org/docs/inline-functions.html).
> Convert updateParameters() to an inline function.

- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt
- app/src/main/res/layout/fragment_audio_player.xml
- app/src/main/res/navigation/nav.xml
- app/src/main/res/xml/audio_player_scene.xml
- app/src/main/res/xml/player_scene.xml
Note that the animations don't always work currently for whatever reason. The mini player itself is fully functional, however.
closes #2688
> Audio mini player

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Fix forward and rewind buttons when player locked

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix that queue controls are visible while player closed

- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
> Fix crash when unregistering downloads receiver

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> Fix shrinked player layout after PiP

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix crashes on audio player transitions

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
> Display the time within the seekbar preview
