- app/src/main/java/com/github/libretube/Subscriptions.kt
- app/src/main/res/layout/fragment_subscriptions.xml
https://github.com/libre-tube/LibreTube/issues/42
Added the SwipeRefreshLayout in the fragment_subscriptions.xml to refresh the content when user pulls down.
I keep the when user click in the tab it refresh the feed, because I don't know which UX do you prefer.
> Add pull down to refresh in subscriptions tab

- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/java/com/github/libretube/SearchFragment.kt
Current behavior:
When we click the full screen button, the orientation changes to landscape and again shifts to portrait.
After we type something in the search and press search button on keyboard, nothing happens.
Expectation:
When we click the full screen button, the orientation should remain in landscape mode until the button is clicked again.
After we type something in the search and press search button on keyboard, the keyboard, search suggestions should close.
> Fix fullscreen button and keyboard search button

- app/src/main/java/com/github/libretube/SearchFragment.kt
The onDismiss event is called automatically sometimes that leads to search results and keyboard closing automatically.
This is caused by my commit: https://github.com/libre-tube/LibreTube/pull/115/commits/89937f4ef6b1860ea8b215e42ebe70abf854cae2
Now I am implementing onItemClickListener.
> Fix search suggestions/keyboard disappearing while typing

- app/src/main/res/layout/fragment_player.xml
Added ability to open links in the video description and copy the description text as requested in Issue #138
> Open links in description and copy description text

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/PlayerFragment.kt
Adds support for PIP (Picture-in-Picture). Currently supports android Oreo (8) and above as lower versions require a workaround.
Closes #59
> PIP Support

- app/src/main/java/com/github/libretube/SettingsActivity.kt
Added a check to see if the user is on android 10 or above if so then use animation otherwise it would end up not showing settings until you go home and back to the app. This was caused by #196
> Fix settings not showing up below android 10 (Q)

- app/src/main/java/com/github/libretube/PlaylistFragment.kt
Fixes #198 
Sometimes? The shared preferences username has different case letters than the response.uploader which causes the delete button to not show up!
In my testing, the last 3 characters in my user id were all upper case where shared preference had them lowercase
> Ignore case for username id

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/Player.kt
- app/src/main/java/com/github/libretube/SettingsActivity.kt
Note to contributors/developers: 
> For each new activity that you add, add this before the `super.onCreate()`: `DynamicColors.applyToActivityIfAvailable(this)`
Or else dynamic color won't be applied.
> Fixed dynamic color on Android 12+

- app/src/main/java/com/github/libretube/PlayerFragment.kt
- app/src/main/res/drawable/ic_aspect_ratio.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
This commit adds a simple button to the video player which allows toggling between the videos aspect ratio (black bars) and zooming into the video to fill the whole screen. Also I've fixed the alignment of the resolution switcher text and icon.
Closes #109 and #188
> add aspect ratio toggle button in exoplayer

- app/src/main/java/com/github/libretube/MainActivity.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/PlaylistOptionsDialog.kt
- app/src/main/java/com/github/libretube/dialogs/ShareDialog.kt
- app/src/main/java/com/github/libretube/dialogs/VideoOptionsDialog.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/util/PipedApi.kt
- app/src/main/res/layout/fragment_playlist.xml
- app/src/main/res/values/strings.xml
> Playlist Options Dialog + Clone Playlist Option

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/adapters/PlaylistsAdapter.kt
- app/src/main/java/com/github/libretube/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/dialogs/AddtoPlaylistDialog.kt
- app/src/main/java/com/github/libretube/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/dialogs/DeleteAccountDialog.kt
- app/src/main/java/com/github/libretube/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/dialogs/PlaylistOptionsDialog.kt
- app/src/main/java/com/github/libretube/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/util/RetrofitInstance.kt
See: #332
To set a different instance for authenticated calls, you just have to set `RetrofitInstance.authUrl`
> Have separate retrofit instance for authenticated calls

- app/src/main/java/com/github/libretube/activities/MainActivity.kt
This fixes when exit searchBar without initializing searchFragment.
> searchBar fix 2

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
When opening a video in an external player picture in picture should not be started.
> Do not stat pip when open video externally

- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
fixes #1275.
tested with the following cases:
| URL | expected result | pass/fail |
| --- | --- | --- |
| https://youtu.be/RDkWagIW6gw | video continues playback | pass |
| https://youtu.be/RDkWagIW6gw?t=123 | starts at 02:03 | pass |
| https://youtu.be/RDkWagIW6gw?t=9m14s | starts at 09:14 | pass |
| https://youtube.com/watch?v=RDkWagIW6gw | video continues playback | pass |
| https://youtube.com/watch?v=RDkWagIW6gw&t=123 |  starts at 02:03 | pass |
| https://youtube.com/watch?v=RDkWagIW6gw&t=9m14s | starts at 09:14 | pass |
> fix: handle duration string timestamps

- .github/workflows/ci.yml
This will fix ci failing for every new pr.
> Continue on error in apk signing process.

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
Before fix: "Show more" button sticks around when collapsing a comment's replies, if said comment has enough replies that it needs to be paginated
https://user-images.githubusercontent.com/848000/198214985-aedbbfac-8fc3-43af-bab0-f858b19886c0.mp4
After fix: "Show more" button is unconditionally hidden when collapsing a comment's replies
https://user-images.githubusercontent.com/848000/198214997-e832a32c-47dd-4167-af7d-2774d8e9a3b5.mp4
> fix: hide "Show more" button when hiding comment replies

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
Prevent duplicate entries in the navigation stack on reselection of the bottom item. Check if the reselected item and currently visible fragment is same, if not navigate to the bottom selected item.
Fix search history appearing at unwanted locations. Remove the search focus after the query is submitted. Fix the search option overflow when searchView is expanded.
Closes #1599, fixes #1948, fixes #1834
> Fix navigation and backstack issues

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/BrightnessHelper.kt
- app/src/main/java/com/github/libretube/util/PreferenceHelper.kt
Brightness changes affect only when the player is in full-screen (landscape) mode. when orientation is changed to portrait, save brightness to shared preferences. It can be restored for later use.
Closes #2046
> Fix brightness inconsistency

- app/src/main/java/com/github/libretube/ui/extensions/SetFormattedHtml.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/res/layout/fragment_player.xml
Fix opening playlist causing `NPE`.
Fix links are not actual hyperlinks. Which causes issues when opening ellipsed links.
There is still one issue, when clicking link it goes into PiP mode. What I have understood is,
When we click on link it trigers `MainActivity#onUserLeaveHint()` which then calls `PlayerFragment#onUserLeaveHint` which leads activity to go into PiP mode.
This problem won't occur when the player is paused because `PlayerFragment#shouldStartPiP()` check for it.
Possible solution could be,
- Pause player when the link is clicked. (Tried setting click listner but seems like Intent is send before the given event)
- Make PiP to fullscreen when the new Intent is received. (I don't think there is any straightforward way to do this)
Closes #1975
> Fix link opening issues

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
If the activity is running in PiP, then start the activity in front.
When the video is in `play` state sometimes it causes `kotlinx.coroutines.JobCancellationException` in `HomeFragment` but I think it's expected behavior since Job is closed forcefully.
Anyways, it's not affecting any behavior (other than making Toast which is handled now) so we can ignore it.
> Fix activity goes in PiP mode on link opening

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
Some links are in plain text so that need to be considered.
When opening link from an external source (e.g. browser) `brightnessHelper` is not initialized which causes NPE
> Fix plain text links and NPE when opening link from external source

- app/src/main/java/com/github/libretube/ui/extensions/SetAspectRatio.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
We can pass aspect ration for pip mode.
However, it will not change ration while already in pip mode.
e.g. When playing short -> go to PiP mode -> next video with different ration -> pip size will be same as during short video.
Closes #2092, closes #1644
> Fix to adopt dynamic aspect ration in PiP mode

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/interfaces/PlayerGestureOptions.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/PlayerGestureControlsView.kt
- app/src/main/java/com/github/libretube/util/BrightnessHelper.kt
- app/src/main/java/com/github/libretube/util/PlayerGestureController.kt
Use `PlayerViewModel.isFullscreen` to instead of **orientation** to decide whether to use gesture controls or not.
Also, added aspect ration PiP mode for offline player.
Closes #2065
> Fix swipe gesture for portrait video

- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
Fix threading issue, video was removed before the database query can use it for deletion which lead to remove wrong video.
Fix empty history view was not showing after removing all videos.
Closes #2127
> Fix watch history deletion

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/BackgroundHelper.kt
The foreground service was still running when using the audio mode and then switching back to video (by pressing play button, play another video, or close app). 
So check when the video `isPlaying` and If `BackgroundMode` service is running first stop it and start video play.
However, i am not able to check what happens when OS kills this foreground service. But, since the notification is cleared in `onDestroy` of `BackgroundMode` service it should work fine. Please give it try.
One more little fix, when `activity` is in PiP then it gives orientation as landscape always, which leads to `setFullscreen` and `BrightnessHelper` thinks it's full-screen :)
(Hope) Closes #1601, closes #1722
> Fix notification freezing issue

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/drawables.xml
Synchronize mini-player buttons with playback state.
Use new image button for player repeat, because changing image resources of `exo_play_pause` will not work since It is frequently updated by [StyledPlayerControlView](https://github.com/google/ExoPlayer/blob/release-v2/library/ui/src/main/java/com/google/android/exoplayer2/ui/StyledPlayerControlView.java#L959).
Closes #2073
> Fix minimized player and repeat button

- app/src/main/java/com/github/libretube/util/BackupHelper.kt
> prioritorize `long` over `int` on restoring settings backup

- app/src/main/res/values/array.xml
This PR changes the list of languages to use their spelling instead of having them all in English.
This list was used:
https://en.wikipedia.org/wiki/List_of_language_names
Someone should double-check it to make sure there are no mistakes.
> Change Language Strings

- app/src/main/java/com/github/libretube/util/PlayerGestureController.kt
Allows pulling down the status bar when watching a video in landscape mode
> Ignore touches to the top of the player

- app/build.gradle
- gradle/libs.versions.toml
Remove the multidex library, as it is not needed on Android 5.0 and later.
> Remove multidex.

- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
- app/src/main/java/com/github/libretube/util/LocaleHelper.kt
Simplify the `LocaleHelper` methods using Kotlin's extensions and property syntax.
> Simplify LocaleHelper methods.

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
Retrieve the primary locale using `ConfigurationCompat.getLocales()` for all Android versions, as `DateTimeFormatter` rejects `null` locales.
> Use ConfigurationCompat.getLocales().

- app/src/main/java/com/github/libretube/util/WindowHelper.kt
Check for a display cutout using [`ViewCompat.getRootWindowInsets()`](https://developer.android.com/reference/androidx/core/view/ViewCompat#getRootWindowInsets(android.view.View)).
> Use ViewCompat.getRootWindowInsets().

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
Use the `awaitAll()` extension function in the playlist export method. Also, remove the use of `runBlocking` in the method as it should not be used in suspend functions.
> Use awaitAll() extension.

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/util/ImportHelper.kt
* Playlists are now getting imported asynchronously
* Video ids are extracted properly from the import file
closes #2608
> Playlist importing bug fixes and performance imporvents

- app/src/main/java/com/github/libretube/ui/extensions/SetDrawables.kt
- app/src/main/java/com/github/libretube/ui/views/DrawableTextView.kt
`setCompoundDrawablesRelativeWithIntrinsicBounds` is available since API level 17 (Android 4.2).
> Remove unnecessary TextViewCompat calls.

- app/src/main/java/com/github/libretube/extensions/ToastFromMainThread.kt
- app/src/main/java/com/github/libretube/helpers/BackupHelper.kt
- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
* Convert backup and import helper classes to singleton objects, and their methods to suspend functions.
* Initialize the activity result launchers directly in the fragment constructor.
> Make backup and restore improvements.

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
More improvements to #2956.
- Controls will not show when video is paused/played with double-tap while they were not already showing.
> Made improvements to player double-tap further.

- app/build.gradle
- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- gradle/libs.versions.toml
Use the [`LifecycleService`](https://developer.android.com/reference/androidx/lifecycle/LifecycleService) class with the download and background mode services.
> Use LifecycleService.

- app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
Release the view bindings in the search fragments when the view is destroyed to avoid memory leaks.
> Release view bindings in search fragments.

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
Use `removeIf()` instead of the `removeAll()` extension function.
> Use removeIf() instead of removeAll().

- app/src/main/java/com/github/libretube/helpers/NetworkHelper.kt
I’m not too sure why the old code was commented out, so please take a look if it’s done right this time. Now it doesn’t say anymore that I have no connection if I’m using [Gnirehtet](https://github.com/Genymobile/gnirehtet).
> Fix no connection with gnirehtet reverse tethering

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
> Improved relative date time formatting

- app/src/main/java/com/github/libretube/ui/dialogs/StatsDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/interfaces/OnlinePlayerOptions.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/main/res/drawable/ic_info.xml
- app/src/main/res/layout/dialog_stats.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
> Stats for nerds dialog containing video info

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
- app/src/main/res/layout/autoplay_countdown.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Autoplay Countdown when the video ended (optional)

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/main/res/values/strings.xml
Add quantity strings to display relative time strings similar to Android 7.0 and later.
> Fix relative time formatting on Android versions below 7.0.

- app/src/main/res/values/strings.xml
Update the "one" relative time strings to allow for proper localization in some locales: https://googlesamples.github.io/android-custom-lint-rules/checks/ImpliedQuantity.md.html
> Fix relative time strings.

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
Added a check for empty playlists.
that prevents error while shuffling private playlists (closes #3248)
> Fix Shuffle Button Error

- app/src/main/java/com/github/libretube/api/obj/Streams.kt
- app/src/main/java/com/github/libretube/db/Converters.kt
- app/src/main/java/com/github/libretube/db/obj/Download.kt
- app/src/main/java/com/github/libretube/db/obj/DownloadItem.kt
- app/src/main/java/com/github/libretube/extensions/Path.kt
- app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
- app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- gradle/libs.versions.toml
* Switch to the [`desugar_jdk_libs_nio`](https://developer.android.com/studio/write/java11-nio-support-table) artifact.
* Use the [`Path`](https://developer.android.com/reference/java/nio/file/Path) and [`Files`](https://developer.android.com/reference/java/nio/file/Files) APIs in the download functionality.
> Use java.nio.file APIs in the download functionality.

- app/src/main/java/com/github/libretube/util/TextUtils.kt
Ignore the time value of the provided timestamp when calculating the time difference.
> Use only the date in relative time formatting.

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Fix crash when closing player

- app/src/main/java/com/github/libretube/extensions/FormatShort.kt
Use [`CompactDecimalFormat`](https://developer.android.com/reference/android/icu/text/CompactDecimalFormat) to format counts on Android 7.0 and later.
**Screenshots**
Before
After
> Use CompactDecimalFormat to format counts.

- app/src/main/res/values/array.xml
Correct Kurdish (Central) native language name and moved to below of Catalan language by language code ckb
> Correct Kurdish (Central) native language name

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/db/dao/LocalPlaylistsDao.kt
- app/src/main/java/com/github/libretube/extensions/ToastFromMainThread.kt
- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/LoginDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/RenamePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> Fix various crashes in the player

- app/src/main/java/com/github/libretube/compat/PictureInPictureCompat.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
Disable picture-in-picture controls on Android Go devices, as the functionality is unavailable on those devices.
> Disable picture-in-picture on Android Go devices.

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> Support sharing `live` links to LibreTube

- app/src/main/java/com/github/libretube/ui/preferences/PlayerSettings.kt
Hide the alternative picture-in-picture controls setting if PiP is not available/enabled.
https://user-images.githubusercontent.com/31027858/228851355-67db22bb-7bfb-4fe2-bea7-4c32ff86a8c9.mp4
> Hide alternative PiP controls setting if PiP is not enabled.

- app/src/main/java/com/github/libretube/services/BackgroundMode.kt
Remove the notification channel creation code from `BackgroundMode`, as the channel is already being created on application startup.
> Remove notification channel creation from BackgroundMode.

- app/src/main/java/com/github/libretube/helpers/WindowHelper.kt
- app/src/main/java/com/github/libretube/ui/extensions/Activity.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
previously we had to tap twice to show controllers. On first tap the status bar will be shown and on the next tap player controller will be shown. This pr fixes this by showing controller on single tap
> Fix two taps required to interact with player when in fullscreen mode

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
There has been an issue when sharing a shorts video while having `Automatic fullscreen on short videos` turned on.
> Fix sharing short videos to the app

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
Free the fragment view bindings when their host fragments are destroyed to avoid memory leaks.
> Free fragment view bindings when their fragments are destroyed.

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/helpers/IntentHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/AboutActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/HelpActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/IntentChooserAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/IntentChooserSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/viewholders/IntentChooserViewHolder.kt
- app/src/main/res/layout/intent_chooser_item.xml
Newer Android versions do always open links inside the default browser of the phone instead of letting the user choose which browser to use. Using `Intent#createChooser` behaves the same way. In order to allow users to choose which browser they actually want to use, the app queries for available packages. Silent contribution from @AudricV, because they're working hard to support the development in the background :)
> In-built browser intent chooser

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> Separate swipe gestures and fullscreen gestures

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
- app/src/main/res/values/strings.xml
* Group new stream notifications together by originating channel, and display a summary notification on Android versions below 7.0.
* Fix the channel navigation.
**Screenshots**
Android 5.0
Android 12
> Improve notification grouping for new streams.

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
- app/src/main/res/drawable/ic_image.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/notification_settings.xml
Display the thumbnails of new streams in their notifications.
**Screenshots**
Android 5.0
Android 8.1
Settings page
> Display stream notification thumbnails.

- app/src/main/res/values/strings.xml
Update the notification preference strings to be more indicative of their functionality.
Before:
After:
> Improve notification preference strings.

- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
* Avoid creating a summary notification if only one new stream is present for a channel.
* Make the individual stream notifications silent if there is more than one per channel.
> Improve stream notifications

- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/ExpandedBottomSheet.kt
Fix way: https://stackoverflow.com/questions/54798186/bottomsheetdialogfragment-allow-user-to-touch-outside
Fix https://github.com/libre-tube/LibreTube/issues/2922
> Ability to interact with player while viewing comments

- README.md
As per Bnyro's notification, We would like to inform you that the LibreTube community on Reddit and Discord will be removed on May 1st, as it is no longer maintained by any of the LibreTube maintainers. These media platforms will no longer be affiliated with LibreTube.
Thank you.
> Removed : Social Media from Readme.

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/history_settings.xml
> Unlimited search history preference

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Closes #3659
Closes #3638 (This fix may work only for html formatted links)
Your PR #3658 creates another problem - Replies fragment will only open when clicked twice on the comment. This PR does not address this issue.
> Improvement to links in description and comment texts.

- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
* Display stream notifications all at once instead of one by one, and create the notification objects concurrently to improve performance.
* Avoid creating single notifications, as there is the possibility of summary notifications not being created in later checks.
> Improve notification creation performance

- app/build.gradle
- app/src/main/java/com/github/libretube/compat/PictureInPictureParamsCompat.kt
- app/src/main/java/com/github/libretube/extensions/SetMetadata.kt
- app/src/main/java/com/github/libretube/extensions/UpdateParameters.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/StatsDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
- app/src/main/res/layout/activity_offline_player.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
- gradle/libs.versions.toml
Regressions (already fixed):
see https://android-developers.googleblog.com/2023/03/media3-is-ready-to-play.html
closes #3600
> Migration to Media3

- app/src/main/java/com/github/libretube/compat/PictureInPictureCompat.kt
The [`PictureInPictureParams#getActions`](https://developer.android.com/reference/android/app/PictureInPictureParams#getActions()) method is only available on API 33 and later, so an error would be thrown on earlier Android versions.
> Avoid possible PIP-related exception on API levels below 33.

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
Issue #1965:
* Search for something
* Play the video
* Clicking back btn would close the search also
Fix:
Disable auto close of search in onMenuItemActionCollapse method call. Search will close when search fragment is removed.
Known Issues:
Search will still close when player fragment is closed.
> Disable search closing when user press back while playing video

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
This is an AOSP bug where destroy of fragment calls invalideMenu of Activity even though the fragment does not participate in menu updates.
https://issuetracker.google.com/issues/244336571
Hence added an workaroud to not invalidate menu when search is in progress.
Closes #1965
> Fix search bar collapse while search in progress

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
* The main goal of these changes is to allow ourselves to have more control over the notification itself since the `PlayerNotificationManager` API is very limited in its possibilities.
* Should be tested intensively on different Android versions once again since the notification behavior differs on recent Android versions
* Kill the background player when swiping its notification away on SDK 27 and below
* Already tested on SDK 33 and SDK 25 by me
closes #3811
closes #3059
> Replace the `PlayerNotificationManager` with a custom implementation

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/values-television/config.xml
- app/src/main/res/values/config.xml
- app/src/main/res/xml/general_settings.xml
Set auto-rotation ON by default in TV
Tested on below two emulators:
Android TV, API 30 -- auto rotation enabled by default and opened in landscape mode
Pixel 2 API 32 with GMS -- auto rotation disabled by default and opened in portrait mode
> Enable auto rotate by default in TV

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/res/drawable/ic_awesome.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/appearance_settings.xml
> Preference to edit the home tab content

- app/src/main/java/com/github/libretube/db/dao/WatchHistoryDao.kt
- app/src/main/java/com/github/libretube/db/dao/WatchPositionDao.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/values/strings.xml
> Show 'mark as unwatched' in video options sheet if already watched

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/adapters/IconsSheetAdapter.kt
Fix ActivityNotFoundException for the main activity by creating a default activity alias and keeping `.MainActivity` enabled.
closes #3092 
closes #3703 
closes #3960 
However for #3960 I don’t think it’s possible to restore the default icon, but in `WelcomeActivity` we can restore it on the first launch.
> Fix: MainActivity crash after icon change

- app/proguard-rules.pro
Upon analysis found below error
java.lang.NoSuchMethodException:
androidx.constraintlayout.motion.widget.KeyAttributes.\<init\> []
Added proguard rules, not able to reproduce the issue with this change.
Fixes #3861
> Miniplayer is not showing properly in release build

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/extensions/Bundle.kt
- app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt
- app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/parcelable/DownloadData.kt
- app/src/main/java/com/github/libretube/parcelable/PlayerData.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Add `PlayerData` class for storing player data as a parcelable object.
> Add PlayerData class

- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
> Fix: hide the nothing here indicator when refreshing home page

- app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt
- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
- app/src/main/res/layout-land/activity_welcome.xml
- app/src/main/res/layout/activity_welcome.xml
> [Welcome Activity] Add button to restore backup and skip instance selection

- app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt
- app/src/main/java/com/github/libretube/ui/models/WelcomeModel.kt
* Improve the `WelcomeModel`.
* Use the `viewModels` extension and remove the view binding variable in `WelcomeActivity`.
> Improve welcome flow

- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
> Fix that the first video using the audio player gets skipped

- app/build.gradle
- gradle/libs.versions.toml
Update the AndroidX Activity and Fragment dependencies to their latest versions ([Activity changelog](https://developer.android.com/jetpack/androidx/releases/activity#1.7.0), [Fragment changelog](https://developer.android.com/jetpack/androidx/releases/fragment#1.6.0))
> Update Activity and Fragment dependencies

- app/src/main/java/com/github/libretube/helpers/AudioHelper.kt
- app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt
Just so you can see it's the same:
MathUtils.clamp function:
```
public static int clamp(int value, int min, int max) {
if (value < min) {
return min;
} else if (value > max) {
return max;
}
return value;
}
```
Kotlin's coerceIn extension function:
```
public fun Int.coerceIn(minimumValue: Int, maximumValue: Int): Int {
if (minimumValue > maximumValue) throw IllegalArgumentException("Cannot coerce value to an empty range: maximum $maximumValue is less than minimum $minimumValue.")
if (this < minimumValue) return minimumValue
if (this > maximumValue) return maximumValue
return this
}
```
> Replace MathUtils.clamp with Kotlin coerceIn

- app/src/main/java/com/github/libretube/util/DeArrowUtil.kt
This should both improve privacy slightly and improve cache hits on the server.
> fix: Sort videoIds before performing DeArrow fetch

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
Since #3774 was merged, when adding a new video to a local playlist all playlists are sorted in newest to oldest order, even when the "Playlists order" preference is set otherwise. This PR makes the playlist sorting respect the preference.
> fix: Sort local playlists based on selected preference

- app/src/main/java/com/github/libretube/ui/sheets/PlayingQueueSheet.kt
- app/src/main/res/layout/queue_bottom_sheet.xml
- app/src/main/res/values/strings.xml
> feat: controls to order queue by date, uploader or views

- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/res/layout/fragment_subscriptions.xml
> feat: show subscribed channels count in subscriptions fragment

- app/src/main/res/values/strings.xml
Change "Export Subscriptions" to "Export subscriptions".
> fix: string capitalization

- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
Fix #4291
Sometimes, the Piped API's response contains comments that were already given in previous pages, so I have added a filter to remove them.
This might not be the best way to do it, but this is my first time working with Kotlin/Android because I found this bug annoying and wanted to do whatever it takes to fix it, so if there is a better way, please do it.
:)
> fix: duplicate comments

- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
* Download and display channel icons for the stream summary notifications. This only occurs if thumbnails are enabled.
* Use the [social category](https://developer.android.com/reference/android/app/Notification#CATEGORY_SOCIAL) for stream notifications.
**Screenshots**
> feat: Show channel icons for stream notifications

- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
> fix: hide add to queue option for playlists when queue empty

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
> fix: don't load audio player thumbnail when data saver mode is on

- app/build.gradle
- app/src/main/java/com/github/libretube/ui/listeners/AudioPlayerThumbnailListener.kt
- app/src/main/java/com/github/libretube/ui/listeners/PlayerGestureController.kt
- app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
* Bump compile SDK to 34 (sources are now available for download).
* Use [`LocalDate.ofInstant()`](https://developer.android.com/reference/java/time/LocalDate#ofInstant(java.time.Instant,%20java.time.ZoneId)).
> refactor: Use LocalDate.ofInstant()

- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
Closes https://github.com/libre-tube/LibreTube/issues/4453.
Because `.toList` is not available on Java < 16, importing a CSV file fail. Using `.collect(Collectors.toList())` fixes the error and allows the user to correctly import the data.
> fix(import): prevent crash when importing

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
Allows to pause the player, while the video is buffering. This can be helpful if the video is constantly buffering, to load a longer timeframe. It is also helpful when simply wanting to pause the video while it is buffering.
To test:
1. Start watching a video
2. Turn off the network
3. Wait until the video starts to buffer
4. Pause the video and turn the network back on
5. Notice how the video does not start playing again once it finished loading
> feat(player): allow pausing when loading

- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
- app/src/main/res/xml/instance_settings.xml
Moves the option to disable the piped proxy to the instance settings page. The proxy preferences align better with the instance settings, given they refer more to video loading than to audio and video configurations. A newcomer might equate proxy settings to "Avoid using a piped instance."
> feat(settings): move proxy settings to instance page

- app/src/main/java/com/github/libretube/api/obj/Instances.kt
- app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Shows the controls once the video ends to indicate to the user that the video has ended.
This addresses an issue I've faced multiple times, mistaking a video's black screen ending for a playback error/buffering.
The controls appear only when autoplay for the next video is off.
> feat: show controls on STATE_ENDED

- app/src/main/java/com/github/libretube/db/dao/SubscriptionGroupsDao.kt
- app/src/main/java/com/github/libretube/ui/sheets/EditChannelGroupSheet.kt
- app/src/main/res/values/strings.xml
Disables the confirm button when creating or modifying a channel group if the group cannot be created. This can either be the case if the group name is empty, or (newly added) no channels are selected.
addresses #3558
> feat(channelGroups): disable confirm button if creation is not possible

- app/schemas/com.github.libretube.db.AppDatabase/14.json
- app/src/main/java/com/github/libretube/api/obj/Instances.kt
- app/src/main/java/com/github/libretube/db/AppDatabase.kt
- app/src/main/java/com/github/libretube/db/DatabaseHolder.kt
- app/src/main/java/com/github/libretube/db/dao/SubscriptionGroupsDao.kt
- app/src/main/java/com/github/libretube/db/obj/SubscriptionGroup.kt
- app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/ChannelGroupsSheet.kt
- app/src/main/res/layout/subscription_group_row.xml
Addresses https://github.com/libre-tube/LibreTube/issues/3558 by allowing channel groups to be rearranged using DnD.
https://github.com/libre-tube/LibreTube/assets/63370021/18d7fbe8-08ff-4feb-a13b-6f18ffeebf1a
This will currently update all groups in the database, this may cause problems with larger sets of groups, in which case it may be worth checking which groups need updating.
Due to the other issues listed in https://github.com/libre-tube/LibreTube/issues/3558 with the Ui, I did not add drag handles.
> feat(channelGroups): allow re-ordering of groups

- app/src/main/java/com/github/libretube/api/obj/Segment.kt
- app/src/main/java/com/github/libretube/enums/SbSkipOptions.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Adds a new SponsorBlock skip option, which only skips the segment when watching the first time. This allows the user to go back and rewatch a segment if they wish to do so. 
When rewatching an already skipped segment, the manual skip option is shown instead.
https://github.com/libre-tube/LibreTube/assets/63370021/d80e73e2-9096-4dae-89d1-3d3d7c32d4b9
> feat: add sponsorblock option to skip only once

- app/src/main/java/com/github/libretube/ui/dialogs/StatsSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/BaseBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/EditChannelGroupSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/IconsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/IntentChooserSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaybackOptionsSheet.kt
Allow dialog view bindings to be garbage collected when the dialog is destroyed.
> fix: Free view bindings in dialogs

- app/src/main/java/com/github/libretube/api/obj/Streams.kt
- app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/StatsSheet.kt
Changes the default video speed for Music videos to 1x. The user can still manually change the speed.
Please note that this can have the side effect of some non-music videos, which are categorized as music videos, being played at the wrong speed.
> feat(player): play music at 1x speed

- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fix an issue on all current versions of Android where it is possible to activate links even when touching outside their line bounds.
> fix: Avoid accidental link clicking

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> fix: crash when an other media session with the same name exists

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: can't download new video while other download in progress

- app/src/main/java/com/github/libretube/helpers/DashHelper.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> feat: disable video track loading while screen off

- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/res/values/strings.xml
> fix: crash when downloaded filename too long

- app/src/main/java/com/github/libretube/extensions/Player.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> feat: allow resuming playback after disconnect

- app/src/main/res/xml/sponsorblock_settings.xml
Removes the dependence of the `sb_contribute_key` on itself, which blocked enabling the setting, as it required itself to be enabled first.
> fix(settings/sponsorblock): allow toggling of contribute setting

- app/src/main/res/values/strings.xml
- app/src/main/res/xml/sponsorblock_settings.xml
Adds a setting to change the used SponsorBlock user ID. Users may want to change (or view) it, as SponsorBlock keeps track of the amount of submitted segments.
> feat(settings/sponsorblock): allow changing sb user id

- app/src/main/java/com/github/libretube/ui/sheets/ChannelGroupsSheet.kt
Fixes a problem with https://github.com/libre-tube/LibreTube/pull/4551 where it was not possible to move over multiple items, e.g. moving an item from bottom to top.
By only saving once the user presses the confirm button, this has the added benefit of allowing the user to undo the reorder by dismissing the sheet.
> fix(channelgroups): update values on confirm

- app/src/main/java/com/github/libretube/extensions/Player.kt
Fixes https://github.com/libre-tube/LibreTube/issues/4784, the player should only pause when it has no buffer to play, not when it is loading, as it always loads, until the allocated buffer is full.
> fix(player): allow pausing while loading

- app/src/main/res/values/strings.xml
Renames the user visible `SponsorBlock Username` string to `SponsorBlock UserID` based on the suggestion from @ajayyy in https://github.com/libre-tube/LibreTube/pull/4749#discussion_r1327891171.
> fix(player): rename SB Username to SB UserID

- app/src/main/java/com/github/libretube/api/obj/ContentItem.kt
- app/src/main/java/com/github/libretube/api/obj/StreamItem.kt
- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/db/obj/LocalPlaylistItem.kt
- app/src/main/java/com/github/libretube/db/obj/WatchHistoryItem.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/workers/NotificationWorker.kt
* Use the upload timestamp in individual stream notifications.
* Make `StreamItem`'s `uploaded` field a non-null value.
> feat: Show upload time in stream notifications

- app/src/main/java/com/github/libretube/extensions/Intent.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/res/layout/fragment_player.xml
Hides the dislikes icon and text when if they are disabled (API returns -1). 
| Before                                                                                                                                     	| After                                                                                                                                      	|
|--------------------------------------------------------------------------------------------------------------------------------------------	|--------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Screenshot of a video showing -1 dislikes](https://github.com/libre-tube/LibreTube/assets/63370021/cf264820-0185-48c0-b0d2-65a7716adba3) 	| …
> fix: hide disabled dislike

- app/src/main/java/com/github/libretube/extensions/Player.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
Fixes a regression in 42d081f04e132bc4ff5dbf408c596bd1f6927992.
Currently, the player only allows pausing when loading, when the current buffer is 0, which is only the case when no network connection is available. The player should pause as long as the current buffered time is less than the minimum buffer needed for playing.
> fix: allow pausing when buffer is less than min buffer

- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
> feat: option to set a different default resolution when not in fullscreen

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/res/drawable/ic_call.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
> feat: option to allow playback during call

- app/src/main/java/com/github/libretube/ui/adapters/ChaptersAdapter.kt
**About fix:** When we are fast scrolling through comments and suddenly click on any comment, sometimes it opens the wrong comment's reply.
**Reason:**  This is only happening on fast scrolling as per my view. The main reason is the position we getting in onViewBinding is wrong. As per my knowledge, it happens when the recycle view recycleView can't find unique layout(on fast scroll). 
**Solution:** This approach means that each item will have a unique view type based on its position in the RecyclerView. So that, also on fast scroll rcv can identify unique views(not the optimised approach but using this approach we can solve this bug). 
Closes #4428
> fix: wrong comment opening bug fixed

- app/src/main/res/layout/comments_row.xml
This is a single-line change.
Previous behaviour: Requires double tap to open any comments. 
Current behaviour: Single click to open comments. (just like YT).
> fix: double tap required to view comment replies

- app/src/main/java/com/github/libretube/api/obj/Streams.kt
- app/src/main/java/com/github/libretube/db/Converters.kt
- app/src/main/java/com/github/libretube/extensions/LocalDate.kt
- app/src/main/java/com/github/libretube/json/SafeInstantSerializer.kt
- app/src/main/java/com/github/libretube/json/SafeLocalDateSerializer.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/views/DescriptionLayout.kt
Properly parse the new date format, which contains a time offset.
> fix: Properly parse date strings

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
> fix: broken offline video duration

- app/src/main/java/com/github/libretube/helpers/WindowHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
- app/src/main/java/com/github/libretube/ui/extensions/Activity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/UndimmedBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/OfflinePlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
- app/src/main/res/layout-land/fragment_player.xml
- app/src/main/res/xml/player_scene.xml
> feat: landscape layout for player page

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: crash when comments are opened when video isn't initialized

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: fullscreen video doesn't use landscape

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/layout/fragment_audio_player.xml
- app/src/main/res/values/style.xml
> refactor: make audio player more accessible and redesign

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> fix: parse playlist descriptions as html

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
This pr fixes restoring from process death. LibreTube navigates to the start fragment after process death, which is not necessary as fragments are restored automatically. On top of that, the bottom navigation bar has its own mechanism of saving and restoring. This sometimes leads to an inconsistent UI state if the last selected navigation item before process death does not have the start fragment as root. The selected menu item does not reflect the displayed tab in this case.
This change actually sets the newly created navigation graph and removes the workaround of navigating to the start fragment to display it. The main activity xml was edited to prevent inflating the navigation graph twice.
> fix: restoring nav after process death

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fix orientation bug where screen get stuck after first orientation change.
Bug was in an if that where removing `SCREEN_ORIENTATION_SENSOR` from `mainActivity.requestedOrientation` ignoring autoFullscreenEnabled prefs.
I'm not sure if I've done some regression on other things as I don't know yet all the app behaviours, every suggestion is welcome.
> fix: auto fullscreen stops working after first rotation

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: related videos are truncated after rotation

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
#5095 fix: Increase subtitle font size in fullscreen
> fix: Increase subtitle font size in fullscreen

- app/build.gradle.kts
looks like there are too many string issues, but this can be merged for future aspects as it prevents many lint issues locally
> chore: add abort on lint function

- app/src/main/java/com/github/libretube/ui/views/DescriptionLayout.kt
> fix: text animation slowly fades out when collapsing description

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
> fix: crash in channel fragment when binding already recycled

- app/src/main/res/xml/audio_player_scene.xml
When doing a swipe up, the audio player couldn't be minimized anymore. I added a click event for the miniplayer to have a transition and set the duration to 500ms.
closes #5205
> fix: audio player stuck when swipe up, correct transition duration

- app/src/main/res/xml/player_settings.xml
When a SliderPreference is processing a preference with a value outside the supported values - valueFrom + x * stepSize an error is shown.
closes #5355
> fix: Error on Settings > Player > Playback speed

- app/src/main/res/layout/video_tag_row.xml
Increases the bottom margin of tags in a video description, letting them display their shadow properly.
| Before                                                                                                                                        	| After                                                                                                                                       	|
|-----------------------------------------------------------------------------------------------------------------------------------------------	|---------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Tags in the description with a broken shadow](https://github.com/libre-tube/LibreTube/assets/63370021/95090371-c …
> fix: properly display tags in description 

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/player_settings.xml
Adds a new setting - `Rich caption rendering` (**false** by default) under Settings > Player > Appearance.
https://github.com/libre-tube/LibreTube/assets/40279132/f5c5d743-c51f-4670-9ba0-165833ad1513
- Translations;
- This setting does not apply mid-video. e.g. If we are watching a video, and change the setting, the changes only reflect once we open a new video. The settings I tested had the same behaviour, but I would like to confirm that is expected, or if I'm missing something;
- I added a new translation under the id - `rich_caption_rendering`. I don't know if there is anything else I must do regarding this addition.
closes #5306
> feat: add "Rich caption rendering" setting

- app/src/main/res/layout-land/fragment_player.xml
- app/src/main/res/layout/fragment_player.xml
I tried many possible colours but ultimately decided to go for `android:background`. These were the reasons:
- With `android:background`, the colour matches the status bar;
- I think it is one of the most aesthetically appealing combinations;
- YouTube follows a similar approach of a darker background with lighter buttons.
Here are the possible colours - [Link to material-components colours](https://github.com/material-components/material-components-android/blob/master/docs/theming/Color.md)
Below are all the combinations I checked. Please let me know if we should choose another colour.
closes #5363
> fix: improve constrast between background and buttons

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
Removed null check from `.let`call.
https://github.com/libre-tube/LibreTube/assets/40279132/7c94664f-da9b-4b3d-b279-20491232bc27
closes #5361
> fix: oldest videos repeatedly displayed when loading channel videos

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
Ensure the player pauses and plays correctly through the action of input devices.
closes #5422
> fix: Incorrect actions management through bluetooth devices

- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
> fix: crash on download menu

- app/src/main/res/values/strings.xml
Improves the summary of the "Load feed in background" option to help users understand what exactly changes when this option is turned on, see https://github.com/libre-tube/LibreTube/pull/5429.
I also think that enabling this option by default is worthwhile, as it both improves the user experience and reduces the load on the server, with very little to no downside.
> chore: improve save feed summary

- app/src/main/res/values/strings.xml
Tweak `swipe_controls_summary` to describe what it does more accurately.
see #5439
> fix: clarify setting description

- app/src/main/java/com/github/libretube/ui/listeners/AudioPlayerThumbnailListener.kt
This problem is not easily replicable, since we need to adjust the volume level very quickly.
https://github.com/libre-tube/LibreTube/assets/40279132/5b6a38d2-4fff-4ca2-9814-a3923c1eb76d
When the volume is adjusted very quickly (faster than 400ms), the following methods are called in the following order
1. `onTouch` with `event.action == MotionEvent.ACTION_DOWN`;
2. `onDown`. Here we call: 
```kotlin
handler.postDelayed(ACTION_INTERVAL, SINGLE_PRESS_TOKEN) { // ACTION_INTERVAL = 400ms
if (!isMoving) listener.onSingleTap()
}
```
3. `onTouch` with `event.action == MotionEvent.ACTION_MOVE`;
4. `onScroll`. Here we set `isMoving = true`;
5. `onTouch` with `event.action == MotionEvent.ACTION_UP`. Here we set `isMoving = false`;
6. At this point, the `handler.postDelayed` runs, and `isMoving` …
> fix: Audio Pausing on quickly volume level adjustment

- app/src/main/java/com/github/libretube/helpers/NavBarHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/xml/activity_main_scene.xml
- Adjusts scene for a smoother transition;
- Fixes vertical positioning when transitioning to mini-player when there are no tabs;
closes #2548 
https://github.com/libre-tube/LibreTube/assets/40279132/0fa8d107-eda9-4f72-953f-e09aad33338f
https://github.com/libre-tube/LibreTube/assets/40279132/15122b62-7bdd-4a16-895d-a2770d41ebbf
https://github.com/libre-tube/LibreTube/assets/40279132/94d24616-eecd-4a89-87d3-8855ca135e9a
https://github.com/libre-tube/LibreTube/assets/40279132/4997baab-6455-4de1-abaa-1e8bfa6b28f8
https://github.com/libre-tube/LibreTube/assets/40279132/1639bf6a-c752-483d-8e8e-1374963b2d0f
https://github.com/libre-tube/LibreTube/assets/40279132/594d146e-0c15-426f-b4c4-666767324737
In my opinion, the downside of this approach is that we have to manually check whether there are …
> fix: Improve player to mini-player transition + bottom space when there are no navigation tabs 

- app/src/main/res/layout/playback_bottom_sheet.xml
- Improve layout of video/audio speed sheet;
- Add `tools:listitem="@layout/slider_label_item"`to recyclerviews, to improve preview;
Please let me know if you think this change didn't result in an improvement.
https://github.com/libre-tube/LibreTube/assets/40279132/f0806605-fcea-438f-ab68-02ef33e52173
https://github.com/libre-tube/LibreTube/assets/40279132/ba8bf452-b8e4-4cfb-9fe2-aebb5d990a93
> style: tweak speed/pitch bottom sheet layout

- app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/res/layout/fragment_home.xml
The main issue being addressed in this PR is the fact that by default the **Max image cache size** setting was empty, instead of "128MB" (that is defaulted when we go to Settings > Advanced > Max image cache size).
For a sample of the issue please take a look at this video (on Google Drive - too large) - [Issue replication video](https://drive.google.com/file/d/100EXLmjwwdKpMxl-F8tkpWWbm--05C3h/view?usp=drive_link)
In the video, a `200` represents a new image loaded, and a `304` or nothing, represents images being retrieved from cache.
To test this on your own, here's a patch with the necessary changes - [analyse-current-state.patch](https://github.com/libre-tube/LibreTube/files/13845315/Analyse_image_load_-_currently_.patch).
- Changes the default value from "" to "128";
- Sets recycler …
> fix: Improve home feed layout and fix issue where incorrect cache size was defaulted.

- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/LegacySubscriptionAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionGroupChannelsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/DownloadOptionsBottomSheet.kt
> fix: can't open playlists

- app/src/main/java/com/github/libretube/ui/views/SingleViewTouchableMotionLayout.kt
Ensure the mini-player can only be dismissed by swiping strictly down from the collapsed state.
closes #5459 
https://github.com/libre-tube/LibreTube/assets/40279132/5e671478-7afa-439e-8a0c-99841e669f4c
> fix: Erratic navbar and miniplayer behaviour.

- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
- When an instance is changed on `InstanceSettings.kt`, the function `instancePref.setOnPreferenceChangeListener` is not being invoked, despite assignment `preference.value = selectedInstance` on L192. This results on `ResettableLazyManager` not being reset, leading to the API not being reloaded, to take into account the new instance selected.
https://github.com/libre-tube/LibreTube/assets/40279132/89e47af1-d957-4b06-9fc4-b48f7eb52ee2
- Ensure `ResettableLazyManager` is reset when a new instance is selected. (Please validate my approach)
https://github.com/libre-tube/LibreTube/assets/40279132/bfb51e45-37a8-430d-8f48-f39b7c14c911
Please let me know if you see a better approach to fixing the issue.
> fix: ResettableLazyManager not being reset on changing instances.

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
This pull request makes the following changes:
Fixes issue #5115
> fix: don't show history when closing video on channel page

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- When scrolling horizontally on the feed, because we are using a recycler view and not resetting the image before a thumbnail is successfully loaded, the image from the view that was previously recycled shows up - The magnitude of this issue depends on the quality of the user's network - fast internet speeds minimize the problem - issue replication below:
https://github.com/libre-tube/LibreTube/assets/40279132/d6320d98-e91e-4726-aee9-29cce98d289f
- Resets the view before loading a new image to it;
https://github.com/libre-tube/LibreTube/assets/40279132/a26f1d4f-32ba-499e-b703-a204d6bc963f
> fix: clear views on VideoAdapter's onBindViewHolder

- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
- app/src/main/java/com/github/libretube/ui/models/TrendsViewModel.kt
this is inspired from rafale rasmos' latest home related pr, now trends has its own lifecycle in a viewmodel and doesnt reloads everytime. especially good for those who keep trends as default.
edit: fook you @reviewdog
> feat: seperate trends fragment into a viewmodel to improve ux

- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
- app/src/main/java/com/github/libretube/ui/models/TrendsViewModel.kt
previously when we swtiched to other tab and came back to trends it reloaded, after switching to viewmodel it is good,
but when we scroll and switch to other tab and come back to trends, it resets to the top position.
this enhances that.
> feat(ui): save scroll position in trends

- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
That change in behavior had been accidentally introduced with #5491
> fix: switch back to home bookmarks layout on home screen

- app/build.gradle.kts
- app/src/main/java/com/github/libretube/ui/adapters/SearchChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchResultsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/callbacks/SearchCallback.kt
- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SearchResultFragment.kt
- app/src/main/java/com/github/libretube/ui/models/SearchResultViewModel.kt
- app/src/main/java/com/github/libretube/ui/models/sources/SearchPagingSource.kt
- gradle/libs.versions.toml
Improve the search functionality using the [Paging library](https://developer.android.com/topic/libraries/architecture/paging/v3-overview).
> refactor: Rewrite search functionality using Paging

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix: don't toggle system bars in player fragment when locking player

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: playing queue actions still visible after miniplayer closed by swipe

- app/build.gradle.kts
- app/src/main/java/com/github/libretube/api/obj/Segment.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/dialogs/VoteForSegmentDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
- gradle/libs.versions.toml
* Updated [AndroidX Collection](https://developer.android.com/jetpack/androidx/releases/collection) to 1.4.0.
* Used `FloatFloatPair` in `Segment` to avoid boxing.
> refactor: Avoid boxing for segment pair

- app/src/main/java/com/github/libretube/helpers/ThemeHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
Fixes issue https://github.com/libre-tube/LibreTube/issues/5574
Correctly displayed colors in the system panel (status bar, navigation bar) in the light mode.
> fix: correctly display colors in system panel

- app/src/main/java/com/github/libretube/api/RetrofitInstance.kt
- app/src/main/java/com/github/libretube/api/obj/PipedInstance.kt
- app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
> feat: display currently selected instance as grayed out if not available

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fixes https://github.com/libre-tube/LibreTube/issues/5626. The playback speed for music videos was set to 1.0x on every event, instead of only once when starting the video.
> fix: set music playback speed only once

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/base/BaseActivity.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix: android back button doesn't work due to dependency upgrade

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/DismissableTimeBar.kt
- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
> feat: don't seek after scrubbing when stopping gesture above timebar

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt
> fix: playback pauses after orientation change

- app/src/main/java/com/github/libretube/helpers/BackupHelper.kt
- app/src/main/java/com/github/libretube/helpers/NotificationHelper.kt
> fix: importing backup doesn't immediately cancel/update notification worker

- app/src/main/java/com/github/libretube/ui/sheets/EditChannelGroupSheet.kt
> fix: channel groups duplicated after updating name

- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
Fixes a problem where the controller was not displayed on the video end screen when "Insert related videos" was disabled. The improved version should now cover edge cases like the last video of a playlist.
I also changed it to show the controller on the end screen permanently (i.e. it doesn't hide after a few seconds), as I found that it was easy to miss.
> feat: improve video end screen

- app/src/main/java/com/github/libretube/extensions/AnyChildFocused.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> feat: dismiss keyboard at back press on search page

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/RouterActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/ImportTempPlaylistDialog.kt
- app/src/main/res/values/strings.xml
> feat: support for importing temporary playlists from YouTube

- app/schemas/com.github.libretube.db.AppDatabase/18.json
- app/src/main/java/com/github/libretube/db/AppDatabase.kt
- app/src/main/java/com/github/libretube/db/DatabaseHolder.kt
- app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt
- app/src/main/java/com/github/libretube/db/obj/DownloadChapter.kt
- app/src/main/java/com/github/libretube/db/obj/DownloadWithItems.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/listeners/SeekbarPreviewListener.kt
- app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt
- app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/OfflinePlayerView.kt
- app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
> feat: chapters support for downloaded videos

- app/src/main/java/com/github/libretube/api/ExternalApi.kt
- app/src/main/java/com/github/libretube/api/obj/DeArrowBody.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/dialogs/SubmitDeArrowDialog.kt
- app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt
- app/src/main/java/com/github/libretube/ui/views/DropdownMenu.kt
- app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/main/res/drawable/ic_dearrow.xml
- app/src/main/res/layout/dialog_submit_dearrow.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/sponsorblock_settings.xml
> feat: support for contributing to DeArrow

- app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
> fix: crash in DownloadService if trying to read dead download item

- app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
> fix: don't show autoplay countdown controls in PiP mode

- app/src/main/java/com/github/libretube/ui/dialogs/SubmitDeArrowDialog.kt
- app/src/main/res/layout/dialog_submit_dearrow.xml
"Ok" button disabled until at least one option is checked
> fix: change DeArrow title submission default

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
This fixes the issue #5765 where the default quality settings should respect aspect ratio. Now when we will open the shorts and default quality setting is 720p then it will auto play with 1280p.
> fix: default quality setting should respect video aspect ratio

- app/src/main/java/com/github/libretube/enums/PlayerEvent.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> feat: pip controls for offline player

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
> feat: now playing notification for downloaded videos

- app/src/main/java/com/github/libretube/api/obj/Subscription.kt
Solves issue of subscription list not loading when channels have old/invalid avatars.
See issue below:
https://github.com/libre-tube/LibreTube/assets/167443179/3d61bab9-52d2-44ab-bb8e-eaa0774c15fb
> fix: crash when importing subscriptions list with invalid avatars

- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
> feat: preference to force maximum audio quality

- app/src/main/java/com/github/libretube/api/RetrofitInstance.kt
- app/src/main/java/com/github/libretube/helpers/ImageHelper.kt
In my testing for debugging #5855, Cronet doesn't appear to be used for API requests and loading images. (At least in the debug builds)
> Fix cronet not being used because of httpClient

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: activity is sometimes unnecessarily restarted

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/res/layout/fragment_watch_history.xml
Affected fragments: SubscriptionsFragment, WatchHistoryFragment, ChannelFragment, PlaylistFragment
closes https://github.com/libre-tube/LibreTube/issues/5808
> fix: scroll state not preserved after rotation change at some places

- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
closes https://github.com/libre-tube/LibreTube/issues/5961
> feat: add pagination to dearrow in feed

- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
> fix: crash when trying to dearrow feed items

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
closes https://github.com/libre-tube/LibreTube/issues/2022
> fix: enter PiP mode when clicking link in description

- app/build.gradle.kts
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- fastlane/metadata/android/en-US/changelogs/53.txt
> fix: navigation bar color when pure theme disabled

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
Fixes an issue, were the Channel video tab name was still using the `VIDEOS_TAB_KEY` as its display name.
| Before                                                                                                                          	| After                                                                                                                                           	|
|---------------------------------------------------------------------------------------------------------------------------------	|-------------------------------------------------------------------------------------------------------------------------------------------------	|
| ![Channel tabbar with wrong name](https://github.com/libre-tube/LibreTube/assets/63370021/acc3ac37-a032-4c92-935e-f6096c5a0e62) 	| …
> fix: use string ressource for channel video tab

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
This prevents concurrent access of the playing queue from different threads by using Java's `synchronized` feature.
closes #6023
> fix: crash when different threads access playing queue

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/PlaylistOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/advanced_settings.xml
closes #6073
Tested with `com.junkfood.seal`, but most other YouTube downloader apps will probably work as well.
> feat: support for external download apps

- app/src/main/java/com/github/libretube/ui/fragments/ChannelFragment.kt
- app/src/main/res/layout/fragment_channel.xml
> style: minor channel page header redesign

- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
Fixes a crash when trying to mark a video as played, that is above the all caught up item.
> fix(SubscriptionsFragment): use null safe call

- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2168463357
> fix: remembered channel group resets when switching fragment

- app/build.gradle.kts
- app/src/main/res/layout/add_channel_to_group_row.xml
- app/src/main/res/layout/dialog_add_channel_to_group.xml
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2182963238
> fix: can't add channel to group if more than ~10 groups

- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
see https://github.com/libre-tube/LibreTube/issues/6134#issuecomment-2196574981
> fix: crash when destroying activity after media session

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: video codec preference doesn't work when HLS enabled

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/libretube/ui/activities/AddToPlaylistActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
> feat: quick share action to add video to playlist

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
- app/src/main/res/layout/dialog_share.xml
> feat: share dialog redesign (including copy link feature)

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/res/layout/fragment_playlist.xml
closes https://github.com/libre-tube/LibreTube/issues/6202
> feat: show total playlist duration

- app/src/main/java/com/github/libretube/ui/fragments/TrendsFragment.kt
> fix: scroll state of trends not preserved

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout-land/fragment_player.xml
- app/src/main/res/layout/fragment_player.xml
- app/src/main/res/values/strings.xml
> feat: button to screenshot/capture current frame

- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- app/src/main/res/layout/fragment_downloads.xml
In this PR, the visibility of some UI elements has been fixed when the list is empty.
> fix: visibility of UI elements in Downloads

- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
> fix: download fails due to filename length

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/db/dao/WatchHistoryDao.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/ui/models/HomeViewModel.kt
closes https://github.com/libre-tube/LibreTube/issues/6292
> feat: watch history pagination

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/LibraryFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/WatchHistoryFragment.kt
- app/src/main/java/com/github/libretube/ui/listeners/PlayerGestureController.kt
- app/src/main/java/com/github/libretube/ui/models/CommonPlayerViewModel.kt
- app/src/main/java/com/github/libretube/ui/models/OfflinePlayerViewModel.kt
- app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
- app/src/main/java/com/github/libretube/ui/views/OnlinePlayerView.kt
This PR splits the PlayerViewModel, so that each fragment or activity where an exoplayer is used has its own properly scoped exoplayer. The result is that an exoplayer is created when the viewmodel of a fragment that needs a player is created and destroyed when the viewmodel is. The exoplayer is no longer recreated upon orientation change.
This means that media keeps playing without interruptions upon orientation change, fixing https://github.com/libre-tube/LibreTube/issues/5754#issuecomment-2230222744
The exoplayer no longer lives inside the player fragment or in the activity scoped viewmodel.
> fix: improve exoplayer scoping

- app/src/main/java/com/github/libretube/ui/dialogs/ShareDialog.kt
> fix: duplicated slash in custom instance's share url

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
This PR is basically the last step of https://github.com/libre-tube/LibreTube/pull/6307
Now you should feel the improvement upon rotation change ;)
The ExoPlayer is no longer stopped on onDestroy, because it is already released in its viewmodel onDestroy method.
> fix: retain exoplayer on orientation change

- gradle/libs.versions.toml
closes https://github.com/libre-tube/LibreTube/issues/6455
> chore: fix failing download for NewPipe Extractor dependency

- app/src/main/java/com/github/libretube/api/ExternalApi.kt
- app/src/main/java/com/github/libretube/api/StreamsExtractor.kt
- app/src/main/java/com/github/libretube/api/obj/VoteInfo.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/instance_settings.xml
fixes #6412 
perhaps adding a toggle under local stream extraction would be useful in case someone doesn't want it? I wasn't sure so I didn't add one.
> feat: RYD support for local stream extraction

- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
- app/src/main/java/com/github/libretube/ui/models/sources/CommentPagingSource.kt
> fix: display comments count (again)

- app/src/main/java/com/github/libretube/extensions/RunCatchingIO.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
> fix: queue refill jobs don't finish when video session ended

- app/src/main/java/com/github/libretube/api/StreamsExtractor.kt
- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/java/com/github/libretube/ui/models/PlayerViewModel.kt
> refactor: error handling for stream extractor responses

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: pip controls don't work if auto-PiP is disabled

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/enums/SupportedClient.kt
- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
- app/src/main/java/com/github/libretube/obj/YouTubeWatchHistoryChannelInfo.kt
- app/src/main/java/com/github/libretube/obj/YouTubeWatchHistoryFileItem.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/preferences/BackupRestoreSettings.kt
- app/src/main/res/layout/video_row.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/import_export_settings.xml
> feat: support for importing watch history from YouTube

- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
It fixes the issue https://github.com/libre-tube/LibreTube/issues/6558
> fix: shuffle button crash when playlist is empty

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
> fix: video fails to play when shared to app with zero navbar tabs

- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/audio_video_settings.xml
closes #6537
Please note that HLS only provides mp4a audio streams, choosing opus only works reliably when using DASH.
> feat: support for selecting audio codec

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fixes https://github.com/libre-tube/LibreTube/issues/6306
> fix: click on video playlist won't load if autoplay is off

- app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt
- app/src/main/java/com/github/libretube/helpers/ContextHelper.kt
- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/ui/sheets/DownloadOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/views/AutoplayCountdownView.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix: hide go to video action when in no internet mode

- app/src/main/java/com/github/libretube/ui/views/DescriptionLayout.kt
> fix: missing separator in video info text

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/helpers/BackgroundHelper.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- app/src/main/res/layout/fragment_download_content.xml
> feat: support for shuffling downloaded audio content

- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/util/NowPlayingNotification.kt
> fix: can't open audio player via notification in downloads

- app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
> fix: unexpected behavior in offline audio player fragment

- app/src/main/java/com/github/libretube/constants/IntentData.kt
- app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt
- app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/dialogs/PlayOfflineDialog.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/layout/dialog_play_offline.xml
- app/src/main/res/values/strings.xml
closes #6325
Added a dialog in PlayerFragment that asks the user, when the selected video has already been downloaded, if they want to play it from the download folder.
Added a setting entry to enable the described feature.
> feat: ask user to play downloaded version if video already downloaded

- app/src/main/java/com/github/libretube/ui/base/BasePreferenceFragment.kt
> fix: don't allow empty input in EditNumberPreference

- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
closes https://github.com/libre-tube/LibreTube/issues/6628
closes https://github.com/libre-tube/LibreTube/issues/6659
> fix: import and export of FreeTube newline format

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchResultsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/java/com/github/libretube/ui/extensions/SetFormattedDuration.kt
- app/src/main/res/values/strings.xml
Replaces the duration of future videos (i.e. Premieres) as 'Upcoming'. This helps to differentiate them from normal videos.
> feat(VideosAdapter): clearly indicate future videos as upcoming

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
Hides the crash dialogs when the application is being developed, as it is obvious and the crash log is easily available
> feat: hide crash dialogs when developing

- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
> fix: don't show audio player when tapping video player notification

- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt
- app/src/main/res/layout/downloaded_media_row.xml
> feat: watch progress support for downloads

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- app/src/main/res/values/strings.xml
> feat: option to only delete watched videos

- app/src/main/java/com/github/libretube/api/PipedApi.kt
- app/src/main/java/com/github/libretube/api/obj/Segment.kt
- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/DescriptionLayout.kt
- app/src/main/res/layout/description_layout.xml
- app/src/main/res/values/array.xml
- app/src/main/res/values/strings.xml
Displays the full SponsorBlock categories as a chip below the video, similar to how the web version works
> feat: display full video sponsorblock categories

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
closes #6777
closes #6778 
closes #6779
> fix: recent player UI regressions

- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
> fix: crash if player view is not attached to lifecycle

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fixes a crash when trying to rotate the player before it is initialized, most likely introduced in https://github.com/libre-tube/LibreTube/pull/6768/commits/76d7c622f8b2664fb614c8cc5a64f6b08ce8f6a4.
> fix: check if streams is initialized

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: crash when opening video in landscape with autofullscreen enabled

- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/DownloadsAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
> feat: reuse existing player when selecting other video while playing

- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
Fixes a regression from 12be4c716cd88fd00f413defd96a7d63292000ed, whereupon trying to play a new video, the player would stay minimized. Additionally, the playing video would be added to the queue, causing the previously played video to be played again.
This is confusing to users, as it breaks the expectation of the player opening when trying to play a video.
Whilst, this causes the player to open, the previously video will continue to play, until the new one is loaded, which might also be unexpected. Maybe it should be paused during the loading time and the spinner be shown?
> fix: maximise player when playing new video

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/models/CommentsViewModel.kt
- app/src/main/java/com/github/libretube/ui/models/CommonPlayerViewModel.kt
- app/src/main/java/com/github/libretube/ui/sheets/ChaptersBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/ExpandablePlayerSheet.kt
> feat: dismiss chapters sheet when minimizing video

- app/src/main/java/com/github/libretube/helpers/DownloadHelper.kt
- app/src/main/java/com/github/libretube/services/DownloadService.kt
- this allows to remove Cronet as per https://github.com/libre-tube/LibreTube/issues/6867 or make it optional, depending on the state of the discussion
- apart from this, the refactor here has been needed for a long time to make the download service more comprehensive
- using OkHttp instead of a `HttpUrlConnection` instance directly allows us to act on a higher level, the HTTP client might also fix some issues experienced by users
possibly resolves https://github.com/libre-tube/LibreTube/issues/5661
> refactor: don't use Cronet directly for downloading

- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
As the Piped API now provides the number of views/upload date for a playlist item, we can display them in the playlist view.
Ref: https://github.com/libre-tube/LibreTube/issues/4401
~~This however leads to the channel being displayed below the views/upload date, which is suboptimal. I'm not sure what is the best way to solve that, either displaying it the info line itself (like for other related streams) or modifying to view to display it above the video info?~~
Since related streams already show channel, views and upload date in this way, I think it is best to continue doing so here. It also works when the information is missing, such as when using created playlists.
| Before …
> feat(Playlist): display views and upload date

- app/src/main/java/com/github/libretube/ui/activities/WelcomeActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/InstancesAdapter.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
> fix: crash when instances refreshed during instance selection (out of bounds)

- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: wrong back order when new fragment opened from audio/video player

- app/src/main/java/com/github/libretube/db/dao/DownloadDao.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/SearchResultsAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/VideosAdapter.kt
- app/src/main/java/com/github/libretube/ui/adapters/WatchHistoryAdapter.kt
- app/src/main/res/drawable/ic_download_folder.xml
- app/src/main/res/layout/video_row.xml
> feat: add badge for downloaded videos

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: play local video version dialog hidden if autofullscreen enabled

- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
Updates the local feed extraction to only fetch channel tabs that are enabled. This cuts down the amount of requests that are sent, but ultimately not used.
As a side note, in my [fork](https://github.com/FineFindus/LibreTube/blob/70c0ab04cdf926f09d115dc3f0389767e1afd0f0/app/src/main/java/com/github/libretube/api/StreamsExtractor.kt#L119) I've experimented with using the more general `FeedInfo` first, to check if there are even new videos available, which seems to reduce the chance to be rate-limited, so it might be worthwhile to take a look at ;)
> feat(LocalFeedRepository): fetch only enabled channel tabs

- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
see https://github.com/libre-tube/LibreTube/pull/6941#issue-2780811740
> feat(LocalFeedExtraction): check if there are any new streams before refreshing channel

- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
Throttles the local feed extration in-order to avoid rate-limiting. This is done, similary to NewPipe, by introducting an articificial delay every 50 fetched feeds of on average 1 second. These values may have to be changed in the future.
Ref: https://github.com/libre-tube/LibreTube/pull/6941#issuecomment-2585206589
> feat(LocalFeedRepository): throttle feed extraction

- app/src/main/java/com/github/libretube/ui/sheets/CommentsSheet.kt
Fixes https://github.com/libre-tube/LibreTube/issues/6010
> Fix back navigation from comment replies

- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
The repeatOnLifecycle block is meant for flows to be collected. Livedata can be observed outside this block.
> Observe comment count outside of lifecycle aware block

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/layout/activity_main.xml
The intention of the OnItemSelectedListener seems to be adding functionality when a menu item is clicked and not overriding how the navigation is performed. This change switches back to the platform navigation implementation, where a fragment is launched single top among other things by default.
> Preserve platform navigation implementation

- app/src/main/java/com/github/libretube/ui/fragments/CommentsMainFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/CommentsRepliesFragment.kt
> fix: only show/hide scroll to top button at end of scrolling

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/activities/NoInternetActivity.kt
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/layout/activity_nointernet.xml
Fixes a lint warning:
FragmentContainerView replaces the <fragment> tag as the preferred way of adding fragments via XML. Unlike the <fragment> tag, FragmentContainerView uses a normal FragmentTransaction under the hood to add the initial fragment, allowing further FragmentTransaction operations on the FragmentContainerView and providing a consistent timing for lifecycle events.
> Migrate to FragmentContainerView

- app/src/main/java/com/github/libretube/helpers/ClipboardHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/AboutActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentPagingAdapter.kt
- app/src/main/java/com/github/libretube/ui/dialogs/ErrorDialog.kt
> feat: show toast message after version text copied

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: crash when rotating phone while player session not yet started

- app/src/main/java/com/github/libretube/ui/fragments/HomeFragment.kt
- app/src/main/res/navigation/nav.xml
Fixes https://github.com/libre-tube/LibreTube/issues/6970
> Fix navigating back home

- app/src/main/java/com/github/libretube/helpers/PlayerHelper.kt
- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
- app/src/main/res/values/array.xml
> fix: preference to only store watch positions for video doesn't work

- app/src/main/java/com/github/libretube/api/obj/StreamItem.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
Skips the check if a video has been already seen (caught up on) for videos which have not been released yet, such as premieres. Doing the check could lead to the all caught up continously displayed for upcoming videos.
> fix(SubscriptionsFragment): skip all-caught-up check for upcoming videos

- app/build.gradle.kts
see https://github.com/libre-tube/LibreTube/issues/6455#issuecomment-2613437397
> chore: don't include encrypted dependency info block blob in builds

- app/src/main/java/com/github/libretube/ui/fragments/DownloadsFragment.kt
This fixes a regression from https://github.com/libre-tube/LibreTube/pull/6971
> fix: downloads adapter empty

- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
- app/src/main/java/com/github/libretube/services/OfflinePlayerService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
> fix: watch position not set for downloaded videos

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
Fixes https://github.com/libre-tube/LibreTube/issues/7025
> fix: navigation without home tab enabled

- app/src/main/java/com/github/libretube/extensions/SetMetadata.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/fragments/AudioPlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
see https://github.com/androidx/media/issues/564 and https://github.com/androidx/media/issues/1552
closes https://github.com/libre-tube/LibreTube/issues/7038
closes https://github.com/libre-tube/LibreTube/issues/7023
> refactor: encode player metadata as JSON string instead of parcelable

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
This fixes an issue, where the watch position would not correctly be saved as the fully watched video. This could occur when the last part of a video was skipped by a SponsorBlock segment.
> fix(player): save watch position on playback end

- app/src/main/java/com/github/libretube/ui/adapters/SubscriptionChannelAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
Fixes https://github.com/libre-tube/LibreTube/issues/7072
Fixes a crash when selecting a different subscription group and going back to the 'all' group
Be aware that this PR removes the local pagination. I think more performance improvements can be gained by making changes to the videos adapter compared to what the local pagination can achieve.
> fix: multiple recyclerview adapter regressions in SubscriptionsFragment

- app/src/main/AndroidManifest.xml
- #7090 Prevent app restart on configuration change(keyboard changes, switching between system dark mode and light mode, etc)
> fix: prevent app restart on configuration change

- app/src/main/java/com/github/libretube/api/PlaylistsHelper.kt
- app/src/main/java/com/github/libretube/api/obj/Playlists.kt
- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/models/PlaylistViewModel.kt
This PR does several things to improve the code quality:
- Perform Database and Network requests in the ViewModel to make it survive configuration changes
- IO work is ensured to be performed in the IO dispatcher by defining it at function level
- Playlists are only fetched once
- AddToPlaylistDialog UI state now survives process death
> refactor: simplify add to playlist dialog

- app/src/main/java/com/github/libretube/ui/views/MarkableTimeBar.kt
The segments drawn on the timeline seem to be off by one pixel. I'm not quite sure what's causing this, as the calculation is done differently to the timeline itself.
Since the calculation depends on the device, and I haven't been able to test this on multiple devices, further testing should be done before merging.
> fix(MarkableTimeBar): align segments to timebar

- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/res/values/strings.xml
Fixes a regression introduced in https://github.com/libre-tube/LibreTube/commit/d34d34e9e6bad1e9e2f32da8bb9ea9aeebb63589, which caused the original fix (https://github.com/libre-tube/LibreTube/commit/111cd1b3507da4240cb339382b63aef622e3bfff) to no longer function correctly.
I also used to opportunity to rename the title of the caught-up item to `All caught up`, in order to avoid having both the title and the subtitle starting with `You`.
> fix(SubscriptionsFragment): skip upcoming videos when adding caught-up

- app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
- app/src/main/java/com/github/libretube/db/dao/SubscriptionsFeedDao.kt
- app/src/main/java/com/github/libretube/repo/FeedRepository.kt
- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
As local feed videos are only fetched once, this can lead to outdated data being displayed in the feed. As we already fetch the metadata when the video is being played, use this data to update the locally stored feed data.
> feat(Feed): update local feed data when watching video

- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
Shorts extracted from the Shorts tab do not have an uploadDate. They are currently saved with their uploadDate set to -1, leading in them to appear at the end of the feed. To fix this, we can use the generic FeedInfo that contains the uploadDate, which also fixes an issue, where old shorts were fetched on every refresh.
Ref: https://github.com/libre-tube/LibreTube/pull/7111
> fix(Feed): extract shorts uploadDate from feedInfo

- app/src/main/java/com/github/libretube/ui/extensions/SetWatchProgressLength.kt
Adds a rounded corner to the watch-progressbar, making it more inline with the general design of the app, as well as how other progressbars are styled.
| Before                                                                                                               	| After                                                                                                                 	|
|----------------------------------------------------------------------------------------------------------------------	|-----------------------------------------------------------------------------------------------------------------------	|
| ![Watchprogress with straight edge](https://github.com/user-attachments/assets/0987e90e-5881-45cf-a632-6934fc4ed475) 	| ![Watchprogress with rounded …
> feat: increase corner-radius of watch-progressbar

- app/src/main/java/com/github/libretube/db/DatabaseHelper.kt
Right now, videos are always marked as watched if they have less than 90% of the time remaining, which is undesirable for long videos. As an example, for a 5h video, it will mark a video as watched if you've got less than 30min remaining, and for a 10h video, it will allow a full hour remaining. It makes sense to impose a minimum time threshold to mark something as being watched, so that you don't end up with that situation for longer videos.
Note that this not only removes the videos from the "continue watching" area in this case, but it also restarts the video when you try to rewatch it, making it more difficult to find your place in the video.
I only chose to mimic what NewPipe does for the numbers since I wanted to use something that has already been established by another app, but …
> fix: bound time remaining to mark a video as watched

- app/src/main/java/com/github/libretube/services/PlaylistDownloadEnqueueService.kt
> fix: playlist download service crashes for video titles with invalid filename characters

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Fixes an issue, where the sponsorblock skip button would remain visible after the video ended.
> fix(Player): hide sponsorblock skip button on video end

- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
> fix: missing playlist name in search results using local extraction

- app/build.gradle.kts
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/res/drawable/splash_anim.xml
- app/src/main/res/drawable/splash_icon.xml
- app/src/main/res/values-night-v31/themes.xml
- app/src/main/res/values-night/colors.xml
- app/src/main/res/values-night/themes.xml
- app/src/main/res/values-v31/themes.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/themes.xml
- gradle/libs.versions.toml
Implement a splash screen similar to the one on Android 12+ for older versions of Android using the Core Splashscreen library.
[This guide](https://developer.android.com/reference/kotlin/androidx/core/splashscreen/SplashScreen) has more information on its features and limitations.
* Before (Android 8.1)
https://github.com/user-attachments/assets/0c88c965-99de-4e5b-a094-4f56c26abbf5
* After (Android 8.1)
https://github.com/user-attachments/assets/8efb1e38-7a79-4f53-918c-58c2c181783e
> feat: Implement splash screen for older Android versions

- app/src/main/java/com/github/libretube/api/ExternalApi.kt
- app/src/main/java/com/github/libretube/api/MediaServiceRepository.kt
- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
- app/src/main/java/com/github/libretube/api/PipedMediaServiceRepository.kt
- app/src/main/java/com/github/libretube/extensions/ShaSum.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
- app/src/main/java/com/github/libretube/ui/dialogs/SubmitSegmentDialog.kt
Implements support for SponsorBlock and DeArrow when using the full local mode.
Please note that I was unable to confirm that DeArrow works correctly, as neither the local nor the Piped API worked, so I'm assuming it is an external failure.
Closes: https://github.com/libre-tube/LibreTube/issues/7193
> feat(local): implement support for SponsorBlock and DeArrow

- app/src/main/AndroidManifest.xml
- app/src/main/res/values-night-v31/themes.xml
- app/src/main/res/values-v31/themes.xml
- app/src/main/res/values/themes.xml
This PR fixes regressions from https://github.com/libre-tube/LibreTube/pull/7154 that caused the offline player activity to be quite awkward for example.
This also ensures that the startup theme is only being used for the MainActivity, and nothing else.
> fix: regressions from recent splash screen addition for Android < 11

- app/src/main/res/values/array.xml
Fix awkward expression for language array (Korean)
> chore: update language name in settings for korean

- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
Fixes an issue, with local mode enabled, users where unable to continously load channel data.
This was caused by the channel nextpage data being stored as a JVM identifier (the default byte array .toString behaviour), rather than the expected base64 encoded string.
Closes: https://github.com/libre-tube/LibreTube/issues/7240
> fix(Local): encode nextpage data as base64

- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
Fixes a parity issue, between Piped and the local mode, where the local mode would now mark the channelOwner's comments, due the `channelOwner` not being set.
> fix(Local): set channelOwner for Comments

- app/src/main/java/com/github/libretube/services/DownloadService.kt
- app/src/main/java/com/github/libretube/util/TextUtils.kt
> fix: thumbnails of videos containing '#' can't be downloaded

- app/build.gradle.kts
- app/src/main/assets/po_token.html
- app/src/main/java/com/github/libretube/api/ExternalApi.kt
- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
- app/src/main/java/com/github/libretube/api/poToken/JavaScriptUtil.kt
- app/src/main/java/com/github/libretube/api/poToken/PoTokenGenerator.kt
- app/src/main/java/com/github/libretube/api/poToken/PoTokenWebView.kt
- gradle/libs.versions.toml
Implements support for locally generating PoTokens using the device web view. This is a direct port of
https://github.com/TeamNewPipe/NewPipe/pull/11955 to native Kotlin.
However, there are some notable differences:
- NewPipe use an additional `PoTokenGenerator` interface. As there is only one implementation right now, this is skipped
- NewPipe handles broken web views on older devices. Since we're increasing `minSdk` in https://github.com/libre-tube/LibreTube/pull/7047, I'm hoping we can get away without
~~It is marked as a draft, since while it does generate valid PoTokens, playback does not work (`Source error: open failed: ENOENT`; help is appreciated).~~
Closes: https://github.com/libre-tube/LibreTube/issues/7065
> feat(StreamsExtractor): generate PoToken

- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlaylistFragment.kt
> fix: video sort order not preserved when starting video from sorted playlist

- app/proguard-rules.pro
- gradle/libs.versions.toml
Switches from the official NewPipeExtractor versions to a [soft fork](https://github.com/libre-tube/NewPipeExtractor), allowing fixes and other improvements that have not yet been merged upstream.
For now, it just contains a fix for working with newer YT player versions and checks if a video is available.
Ref: https://github.com/TeamNewPipe/NewPipeExtractor/pull/1290
Ref: https://github.com/libre-tube/LibreTube/pull/7113
> build: use NewPipeExtractor fork

- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
- build.gradle.kts
YouTube has started to insert Members only videos into the normal video feed. As there not watchable without signing in, they only clutter the subscription feed.
This filters them out before they're displayed.
Requires https://github.com/TeamNewPipe/NewPipeExtractor/pull/1280
This is still a draft as extractor PR is not yet merged. It might also make sense to still store the videos, so they can be used when deciding if a full channel fetch is needed?
> feat(LocalFeedRepository): filter members only videos

- app/src/main/java/com/github/libretube/repo/LocalFeedRepository.kt
Speeds up the local feed extraction, by fetching more feeds concurrently and only applying a large timeout after fetching the full channels. This is based on the idea that YouTube's RSS feeds (extracted by the generic `FeedInfo`) have [no/much less rate-limiting](https://github.com/TeamNewPipe/NewPipe/issues/11817), likely due to the nature of RSS readers. I couldn't find an explicit statement from YouTube about that, but it makes sense. I've also [increased to amount of concurrently fetched feeds](https://github.com/libre-tube/LibreTube/commit/7503ef122daf45c9929e3ab122e6bc4b18adc314) in my fork for the last couple of months and had no noticeable impact so far.
A small timeout after each chunk is still applied, to be a good citizen of the web and not overwhelm/spam the server.
The used …
> perf(LocalFeedRepository): speed up local feed extraction

- .github/workflows/codeql-analysis.yml
The changes are based on the example codeql workflow setup from the GitHub actions page.
> ci: fix codeql

- app/src/main/java/com/github/libretube/api/SubscriptionHelper.kt
> fix: always use account subscriptions repository if logged in to Piped

- app/src/main/java/com/github/libretube/ui/adapters/SearchResultsAdapter.kt
> fix: channel avatar missing in subscriptions list when subbed from search

- app/src/main/java/com/github/libretube/helpers/ImportHelper.kt
Fixes an issue, where subscription export would be invalid, due to malformed URLs, which are missing the channel path segment.
> fix(Backup): use channel URL for subscription export

- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
- app/src/main/java/com/github/libretube/services/OnlinePlayerService.kt
> fix: SponsorBlock segments of previous video not cleared when starting next

- app/src/main/java/com/github/libretube/services/AbstractPlayerService.kt
- app/src/main/java/com/github/libretube/util/PlayingQueue.kt
Fixes an issue, where the `currentStream` was not cleared when closing the player. This could lead to an issue, where not all video options where displayed, even if the video was no longer playing.
Ref: https://github.com/libre-tube/LibreTube/commit/f262210ef74f268445f8831bd51f54ac0cb1c019
> fix(player): clear current stream when closing player

- app/src/main/java/com/github/libretube/LibreTubeApp.kt
- app/src/main/java/com/github/libretube/constants/PreferenceKeys.kt
- app/src/main/java/com/github/libretube/enums/SbSkipOptions.kt
- app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/res/values/array.xml
Drops the `VISIBLE` option for SponsorBlock, as it provides no additional value and leads to bad UX, as a user is able to see the segment, but able to skip it.
Existing users are migrated to the `MANUAL` option. To achieve this, new supporting code is introduced, that allows us to automatically migrate preferences.
Ref: https://github.com/libre-tube/LibreTube/issues/7384#issuecomment-2860415128
Ref: https://github.com/libre-tube/LibreTube/commit/f5c40157f3e38f019edbbc2568e7c869ffd4f968
Ref: https://github.com/libre-tube/LibreTube/commit/9ceb258881bebb5ee36b6105b491e021930b07bd
> feat(Preferences/SponsorBlock): drop `VISIBLE` option 

- app/src/main/java/com/github/libretube/helpers/PreferenceHelper.kt
Uses the `MIGRATION` length to determine the appropriate migrations to be run. This works, as opposed to Room migrations, there is no `AutoMigration`, i.e. no version increase without a corresponding `PreferenceMigration`. By automatically determining the preference version, we avoid issues, where a new migration is created, but never actually run, as the version is not incremented.
Ref: https://github.com/libre-tube/LibreTube/commit/c746647041515ed8e52077753978fb099a53a543
> refactor(Preferences): use `MIGRATION` length as version

- app/src/main/java/com/github/libretube/helpers/NavigationHelper.kt
- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
- app/src/main/java/com/github/libretube/ui/adapters/PlaylistAdapter.kt
- app/src/main/java/com/github/libretube/ui/fragments/SubscriptionsFragment.kt
- app/src/main/java/com/github/libretube/ui/sheets/DownloadOptionsBottomSheet.kt
- app/src/main/java/com/github/libretube/ui/sheets/VideoOptionsBottomSheet.kt
> fix: queue missing when playing playlist video in background

- app/src/main/java/com/github/libretube/api/InstanceRepository.kt
- app/src/main/java/com/github/libretube/ui/models/WelcomeViewModel.kt
- app/src/main/java/com/github/libretube/ui/preferences/InstanceSettings.kt
The `Context` parameter was unused in the `InstanceRepository` constructor and has been removed. This simplifies the class and its instantiation.
> Chore: Remove context parameter from InstanceRepository

- app/src/main/res/layout-land/fragment_player.xml
Reverts libre-tube/LibreTube#7475
Breaks mobile landscape UI, for reference:
> chore: revert "Improve landscape UI"

- app/src/main/res/layout-land/fragment_player.xml
- app/src/main/res/values-large/dimens.xml
- app/src/main/res/values-xlarge/dimens.xml
- app/src/main/res/values/dimens.xml
see https://github.com/libre-tube/LibreTube/pull/7475
closes #7446
> feat: dynamically scale landscape player based on screen size

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
> fix: audio player autoplay doesn't work if autoplay countdown enabled

- app/src/main/java/com/github/libretube/api/NewPipeMediaServiceRepository.kt
- app/src/main/java/com/github/libretube/api/obj/Comment.kt
- app/src/main/java/com/github/libretube/ui/adapters/CommentPagingAdapter.kt
- note that this only works with local streams extraction, Piped doesn't support it
> fix: comment time not localized

- app/src/main/java/com/github/libretube/helpers/BrightnessHelper.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- previously it's been hard to change the brightness in the lower dimmed area, e.g. what you do during night
- by using logarithmic scaling (using Android's formula), the brightness controls are more intuitive
> feat: logarithmic brightness scaling

- app/src/main/java/com/github/libretube/ui/activities/OfflinePlayerActivity.kt
- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
- app/src/main/res/layout-land/fragment_player.xml
- app/src/main/res/layout/activity_offline_player.xml
- app/src/main/res/layout/custom_exo_player_view.xml
- app/src/main/res/layout/custom_exo_player_view_template.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
- app/src/main/res/layout/fragment_player.xml
Motivation:
- We previously duplicated the code to embed the views that are required by the player (e.g. the +10 seek indicator, autoplay countdown, ...) by pasting them everywhere a PlayerView instead is defined in XML
- This way is much cleaner and removes the duplicated code
- The changes also allow us to have more control over the ExoPlayer views inbuild components and use view bindings on it, which hasn't been possible before this PR.
Caveats:
- However, we unfortunately need to create a wrapper `custom_exo_player_view` around the real views, because `PlayerView` replaces `@id/exo_controller_placeholder` with the actual controller view in its constructor, so there's no way that we can prevent that behavior. That causes `custom_exo_player_view` not to be inflatable, because the view …
> refactor: move player related sub-views to its own binding

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
- app/src/main/java/com/github/libretube/ui/views/DescriptionLayout.kt
Fixes a regression, where the description layout could still be expanded, when loading a new video, leading to only a blank layout being displayed.
Ref: https://github.com/libre-tube/LibreTube/pull/7526
> fix: collapse description when loading new video

- app/proguard-rules.pro
Fixes a regression, where in release mode the auto-generated protobuf classes would be removed, leading to a runtime error.
This could lead to indefinite loading when trying to interact with online playlist.
Ref: https://github.com/libre-tube/LibreTube/pull/7568
> build: keep NewPipeExtractor auto-generated proto classes

- app/src/main/java/com/github/libretube/ui/dialogs/DownloadDialog.kt
- app/src/main/res/layout/dialog_download.xml
Hides the download title, as it is not otherwise exposed to the user and just used for internally storing the downloaded items.
> feat: remove download title

- app/src/main/java/com/github/libretube/ui/adapters/CommentPagingAdapter.kt
Fixes an issue, where the creator reply indicator would be displayed multiple times in the reply page. This is caused by android re-using the view in the recyclerview, but not resetting the visibility of the imageview.
> fix(UI/Comments): only show creator reply indicator for the initial comment

- app/src/main/java/com/github/libretube/ui/dialogs/CreatePlaylistDialog.kt
- app/src/main/java/com/github/libretube/ui/views/DropdownMenu.kt
- app/src/main/res/layout/dialog_create_playlist.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/style.xml
This PR separate `clone playlist` and `create playlist` into  separate view via spinner.
Having 2 options in the same UI while the user only able to proceed with just one of them is kind of bad UX, I think?  
Before changes:
After changes:
> feat: separate 'clone' and 'create' when creating a new playist

- app/src/main/java/com/github/libretube/ui/dialogs/AddToPlaylistDialog.kt
- app/src/main/res/layout/dialog_add_to_playlist.xml
Slight UI impovement to avoid confusion.
Dialog before:
Dialog after:
This PR also includes **fix**:
-After the user deleted all playlists, if they try to add a video to a playlist by triggering this dialog, the app crashes.
> feat: disable 'Add to playlist' button and spinner when there is no playlist available

- app/src/main/java/com/github/libretube/ui/activities/MainActivity.kt
There is a possibility that the paddings are not properly applied when exiting from player's fullscreen.
Fixes #7616
> fix: appbar and bottom navigation paddings not properly applied

- app/src/main/res/layout/double_tap_overlay.xml
- app/src/main/res/layout/exo_styled_player_control_view.xml
I also notice the skip segment button appears at the left side in rtl mode. The video is progressing from left to right so the skip segment button on the left side seems kind of unintuitive,  I think? I wanted to hardcode it on the right side but realized it's been there for quite some time so it might make some people unhappy if it's moved so I just left it untouched.
> fix(player ui): seek and skip buttons appear at opposite side in rtl mode

- app/src/main/java/com/github/libretube/util/TextUtils.kt
- app/src/test/java/com/github/libretube/TextParserTest.kt
Previously when trying to submit a sponsorblock segment, if the time exceed 1 hour, the time conversion resulted in a wrong value and caused the segment to be submitted in the wrong place of the video
> fix(sponsorblock): segment time not properly parsed if exceeds 1 hour

- app/src/main/java/com/github/libretube/ui/fragments/PlayerFragment.kt
Now the search bar's focus is being cleared every time the player is maximized.
> fix: keyboard showing up in player screen

- app/src/main/java/com/github/libretube/ui/preferences/GeneralSettings.kt
> fix: location category is empty on A13+
